// @generated by vocabulary/generate.mjs from vocabulary/vocabulary.json. DO NOT EDIT.
//
// Run `node vocabulary/generate.mjs` after changing the manifest.
// scripts/vocabulary-parity.mjs fails when this file and the manifest disagree.

/// Every fact kind the engine can emit. Declared to the CLI in the `scan_started` handshake so an incompatible pairing is refused before any fact is ingested.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum FactKind {
    FileDetected,
    ImportUsed,
    ReExportUsed,
    ExportedSymbol,
    SymbolCalled,
    DataOperationDetected,
    RouteDeclared,
    FileRoleDetected,
    RouteFlavorDetected,
    TestDeclared,
    AuthGuardCalled,
    RouteReturnsResponse,
    CallbackBoundaryDetected,
    MiddlewareDeclared,
    MiddlewareMatcherDeclared,
    MiddlewareProtectsRoute,
    RequestInputRead,
    SessionRead,
    TenantSource,
    TenantGuardCalled,
    AuthorizationGuardCalled,
    RequestValidationCalled,
    ValidatedInputUsed,
    OutboundRequestCalled,
    RawSqlCalled,
    ParameterizedSqlUsed,
    CsrfGuardCalled,
    RateLimitGuardCalled,
    CorsPolicyDeclared,
    SensitiveFieldDeclared,
    ResponseEmitsField,
    SerializerCalled,
    SecretRead,
    SecretSourceRead,
    DataModelDeclared,
    DataModelFieldDeclared,
    DataModelRelationDeclared,
}

impl FactKind {
    /// Every member, in manifest order.
    pub const ALL: &'static [FactKind] = &[
        FactKind::FileDetected,
        FactKind::ImportUsed,
        FactKind::ReExportUsed,
        FactKind::ExportedSymbol,
        FactKind::SymbolCalled,
        FactKind::DataOperationDetected,
        FactKind::RouteDeclared,
        FactKind::FileRoleDetected,
        FactKind::RouteFlavorDetected,
        FactKind::TestDeclared,
        FactKind::AuthGuardCalled,
        FactKind::RouteReturnsResponse,
        FactKind::CallbackBoundaryDetected,
        FactKind::MiddlewareDeclared,
        FactKind::MiddlewareMatcherDeclared,
        FactKind::MiddlewareProtectsRoute,
        FactKind::RequestInputRead,
        FactKind::SessionRead,
        FactKind::TenantSource,
        FactKind::TenantGuardCalled,
        FactKind::AuthorizationGuardCalled,
        FactKind::RequestValidationCalled,
        FactKind::ValidatedInputUsed,
        FactKind::OutboundRequestCalled,
        FactKind::RawSqlCalled,
        FactKind::ParameterizedSqlUsed,
        FactKind::CsrfGuardCalled,
        FactKind::RateLimitGuardCalled,
        FactKind::CorsPolicyDeclared,
        FactKind::SensitiveFieldDeclared,
        FactKind::ResponseEmitsField,
        FactKind::SerializerCalled,
        FactKind::SecretRead,
        FactKind::SecretSourceRead,
        FactKind::DataModelDeclared,
        FactKind::DataModelFieldDeclared,
        FactKind::DataModelRelationDeclared,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            FactKind::FileDetected => "file_detected",
            FactKind::ImportUsed => "import_used",
            FactKind::ReExportUsed => "re_export_used",
            FactKind::ExportedSymbol => "exported_symbol",
            FactKind::SymbolCalled => "symbol_called",
            FactKind::DataOperationDetected => "data_operation_detected",
            FactKind::RouteDeclared => "route_declared",
            FactKind::FileRoleDetected => "file_role_detected",
            FactKind::RouteFlavorDetected => "route_flavor_detected",
            FactKind::TestDeclared => "test_declared",
            FactKind::AuthGuardCalled => "auth_guard_called",
            FactKind::RouteReturnsResponse => "route_returns_response",
            FactKind::CallbackBoundaryDetected => "callback_boundary_detected",
            FactKind::MiddlewareDeclared => "middleware_declared",
            FactKind::MiddlewareMatcherDeclared => "middleware_matcher_declared",
            FactKind::MiddlewareProtectsRoute => "middleware_protects_route",
            FactKind::RequestInputRead => "request_input_read",
            FactKind::SessionRead => "session_read",
            FactKind::TenantSource => "tenant_source",
            FactKind::TenantGuardCalled => "tenant_guard_called",
            FactKind::AuthorizationGuardCalled => "authorization_guard_called",
            FactKind::RequestValidationCalled => "request_validation_called",
            FactKind::ValidatedInputUsed => "validated_input_used",
            FactKind::OutboundRequestCalled => "outbound_request_called",
            FactKind::RawSqlCalled => "raw_sql_called",
            FactKind::ParameterizedSqlUsed => "parameterized_sql_used",
            FactKind::CsrfGuardCalled => "csrf_guard_called",
            FactKind::RateLimitGuardCalled => "rate_limit_guard_called",
            FactKind::CorsPolicyDeclared => "cors_policy_declared",
            FactKind::SensitiveFieldDeclared => "sensitive_field_declared",
            FactKind::ResponseEmitsField => "response_emits_field",
            FactKind::SerializerCalled => "serializer_called",
            FactKind::SecretRead => "secret_read",
            FactKind::SecretSourceRead => "secret_source_read",
            FactKind::DataModelDeclared => "data_model_declared",
            FactKind::DataModelFieldDeclared => "data_model_field_declared",
            FactKind::DataModelRelationDeclared => "data_model_relation_declared",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "file_detected" => Some(FactKind::FileDetected),
            "import_used" => Some(FactKind::ImportUsed),
            "re_export_used" => Some(FactKind::ReExportUsed),
            "exported_symbol" => Some(FactKind::ExportedSymbol),
            "symbol_called" => Some(FactKind::SymbolCalled),
            "data_operation_detected" => Some(FactKind::DataOperationDetected),
            "route_declared" => Some(FactKind::RouteDeclared),
            "file_role_detected" => Some(FactKind::FileRoleDetected),
            "route_flavor_detected" => Some(FactKind::RouteFlavorDetected),
            "test_declared" => Some(FactKind::TestDeclared),
            "auth_guard_called" => Some(FactKind::AuthGuardCalled),
            "route_returns_response" => Some(FactKind::RouteReturnsResponse),
            "callback_boundary_detected" => Some(FactKind::CallbackBoundaryDetected),
            "middleware_declared" => Some(FactKind::MiddlewareDeclared),
            "middleware_matcher_declared" => Some(FactKind::MiddlewareMatcherDeclared),
            "middleware_protects_route" => Some(FactKind::MiddlewareProtectsRoute),
            "request_input_read" => Some(FactKind::RequestInputRead),
            "session_read" => Some(FactKind::SessionRead),
            "tenant_source" => Some(FactKind::TenantSource),
            "tenant_guard_called" => Some(FactKind::TenantGuardCalled),
            "authorization_guard_called" => Some(FactKind::AuthorizationGuardCalled),
            "request_validation_called" => Some(FactKind::RequestValidationCalled),
            "validated_input_used" => Some(FactKind::ValidatedInputUsed),
            "outbound_request_called" => Some(FactKind::OutboundRequestCalled),
            "raw_sql_called" => Some(FactKind::RawSqlCalled),
            "parameterized_sql_used" => Some(FactKind::ParameterizedSqlUsed),
            "csrf_guard_called" => Some(FactKind::CsrfGuardCalled),
            "rate_limit_guard_called" => Some(FactKind::RateLimitGuardCalled),
            "cors_policy_declared" => Some(FactKind::CorsPolicyDeclared),
            "sensitive_field_declared" => Some(FactKind::SensitiveFieldDeclared),
            "response_emits_field" => Some(FactKind::ResponseEmitsField),
            "serializer_called" => Some(FactKind::SerializerCalled),
            "secret_read" => Some(FactKind::SecretRead),
            "secret_source_read" => Some(FactKind::SecretSourceRead),
            "data_model_declared" => Some(FactKind::DataModelDeclared),
            "data_model_field_declared" => Some(FactKind::DataModelFieldDeclared),
            "data_model_relation_declared" => Some(FactKind::DataModelRelationDeclared),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for FactKind {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for FactKind {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for FactKind {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        FactKind::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown fact_kind \"{raw}\": this engine and its caller disagree about the fact_kind vocabulary"
            ))
        })
    }
}

/// Node kinds in the fact graph. Part of the `scan_started` handshake alongside fact kinds: before W5 the engine emitted these as bare strings, so a kind the CLI did not know produced a Zod enum failure and exit 1 rather than the exit-3 refusal the handshake exists to give.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum GraphNodeKind {
    Repo,
    Package,
    Artifact,
    File,
    FileVersion,
    Module,
    Symbol,
    ImportDecl,
    ExportDecl,
    Callsite,
    DataStore,
    DataOperation,
    Endpoint,
    ReExport,
    Route,
    FileRole,
    Diagnostic,
    Finding,
}

impl GraphNodeKind {
    /// Every member, in manifest order.
    pub const ALL: &'static [GraphNodeKind] = &[
        GraphNodeKind::Repo,
        GraphNodeKind::Package,
        GraphNodeKind::Artifact,
        GraphNodeKind::File,
        GraphNodeKind::FileVersion,
        GraphNodeKind::Module,
        GraphNodeKind::Symbol,
        GraphNodeKind::ImportDecl,
        GraphNodeKind::ExportDecl,
        GraphNodeKind::Callsite,
        GraphNodeKind::DataStore,
        GraphNodeKind::DataOperation,
        GraphNodeKind::Endpoint,
        GraphNodeKind::ReExport,
        GraphNodeKind::Route,
        GraphNodeKind::FileRole,
        GraphNodeKind::Diagnostic,
        GraphNodeKind::Finding,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            GraphNodeKind::Repo => "repo",
            GraphNodeKind::Package => "package",
            GraphNodeKind::Artifact => "artifact",
            GraphNodeKind::File => "file",
            GraphNodeKind::FileVersion => "file_version",
            GraphNodeKind::Module => "module",
            GraphNodeKind::Symbol => "symbol",
            GraphNodeKind::ImportDecl => "import_decl",
            GraphNodeKind::ExportDecl => "export_decl",
            GraphNodeKind::Callsite => "callsite",
            GraphNodeKind::DataStore => "data_store",
            GraphNodeKind::DataOperation => "data_operation",
            GraphNodeKind::Endpoint => "endpoint",
            GraphNodeKind::ReExport => "re_export",
            GraphNodeKind::Route => "route",
            GraphNodeKind::FileRole => "file_role",
            GraphNodeKind::Diagnostic => "diagnostic",
            GraphNodeKind::Finding => "finding",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "repo" => Some(GraphNodeKind::Repo),
            "package" => Some(GraphNodeKind::Package),
            "artifact" => Some(GraphNodeKind::Artifact),
            "file" => Some(GraphNodeKind::File),
            "file_version" => Some(GraphNodeKind::FileVersion),
            "module" => Some(GraphNodeKind::Module),
            "symbol" => Some(GraphNodeKind::Symbol),
            "import_decl" => Some(GraphNodeKind::ImportDecl),
            "export_decl" => Some(GraphNodeKind::ExportDecl),
            "callsite" => Some(GraphNodeKind::Callsite),
            "data_store" => Some(GraphNodeKind::DataStore),
            "data_operation" => Some(GraphNodeKind::DataOperation),
            "endpoint" => Some(GraphNodeKind::Endpoint),
            "re_export" => Some(GraphNodeKind::ReExport),
            "route" => Some(GraphNodeKind::Route),
            "file_role" => Some(GraphNodeKind::FileRole),
            "diagnostic" => Some(GraphNodeKind::Diagnostic),
            "finding" => Some(GraphNodeKind::Finding),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for GraphNodeKind {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for GraphNodeKind {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for GraphNodeKind {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        GraphNodeKind::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown graph_node_kind \"{raw}\": this engine and its caller disagree about the graph_node_kind vocabulary"
            ))
        })
    }
}

/// Edge kinds in the fact graph. Same handshake as node kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum GraphEdgeKind {
    RepoHasFile,
    FileHasVersion,
    FileDefinesModule,
    FileHasRole,
    FileContainsSymbol,
    ModuleImportsModule,
    ImportDeclReferencesModule,
    ImportResolvesToModule,
    ImportResolvesToSymbol,
    ModuleExportsSymbol,
    RouteDeclaredInFile,
    RouteHandledBySymbol,
    RouteHasEndpoint,
    ModuleReexportsModule,
    ReexportResolvesToSymbol,
    CallsiteReferencesSymbol,
    DataOperationReadsDataStore,
    DataOperationWritesDataStore,
    DataOperationDeletesDataStore,
    DataOperationTouchesDataStore,
    FindingHasEvidence,
}

impl GraphEdgeKind {
    /// Every member, in manifest order.
    pub const ALL: &'static [GraphEdgeKind] = &[
        GraphEdgeKind::RepoHasFile,
        GraphEdgeKind::FileHasVersion,
        GraphEdgeKind::FileDefinesModule,
        GraphEdgeKind::FileHasRole,
        GraphEdgeKind::FileContainsSymbol,
        GraphEdgeKind::ModuleImportsModule,
        GraphEdgeKind::ImportDeclReferencesModule,
        GraphEdgeKind::ImportResolvesToModule,
        GraphEdgeKind::ImportResolvesToSymbol,
        GraphEdgeKind::ModuleExportsSymbol,
        GraphEdgeKind::RouteDeclaredInFile,
        GraphEdgeKind::RouteHandledBySymbol,
        GraphEdgeKind::RouteHasEndpoint,
        GraphEdgeKind::ModuleReexportsModule,
        GraphEdgeKind::ReexportResolvesToSymbol,
        GraphEdgeKind::CallsiteReferencesSymbol,
        GraphEdgeKind::DataOperationReadsDataStore,
        GraphEdgeKind::DataOperationWritesDataStore,
        GraphEdgeKind::DataOperationDeletesDataStore,
        GraphEdgeKind::DataOperationTouchesDataStore,
        GraphEdgeKind::FindingHasEvidence,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            GraphEdgeKind::RepoHasFile => "REPO_HAS_FILE",
            GraphEdgeKind::FileHasVersion => "FILE_HAS_VERSION",
            GraphEdgeKind::FileDefinesModule => "FILE_DEFINES_MODULE",
            GraphEdgeKind::FileHasRole => "FILE_HAS_ROLE",
            GraphEdgeKind::FileContainsSymbol => "FILE_CONTAINS_SYMBOL",
            GraphEdgeKind::ModuleImportsModule => "MODULE_IMPORTS_MODULE",
            GraphEdgeKind::ImportDeclReferencesModule => "IMPORT_DECL_REFERENCES_MODULE",
            GraphEdgeKind::ImportResolvesToModule => "IMPORT_RESOLVES_TO_MODULE",
            GraphEdgeKind::ImportResolvesToSymbol => "IMPORT_RESOLVES_TO_SYMBOL",
            GraphEdgeKind::ModuleExportsSymbol => "MODULE_EXPORTS_SYMBOL",
            GraphEdgeKind::RouteDeclaredInFile => "ROUTE_DECLARED_IN_FILE",
            GraphEdgeKind::RouteHandledBySymbol => "ROUTE_HANDLED_BY_SYMBOL",
            GraphEdgeKind::RouteHasEndpoint => "ROUTE_HAS_ENDPOINT",
            GraphEdgeKind::ModuleReexportsModule => "MODULE_REEXPORTS_MODULE",
            GraphEdgeKind::ReexportResolvesToSymbol => "REEXPORT_RESOLVES_TO_SYMBOL",
            GraphEdgeKind::CallsiteReferencesSymbol => "CALLSITE_REFERENCES_SYMBOL",
            GraphEdgeKind::DataOperationReadsDataStore => "DATA_OPERATION_READS_DATA_STORE",
            GraphEdgeKind::DataOperationWritesDataStore => "DATA_OPERATION_WRITES_DATA_STORE",
            GraphEdgeKind::DataOperationDeletesDataStore => "DATA_OPERATION_DELETES_DATA_STORE",
            GraphEdgeKind::DataOperationTouchesDataStore => "DATA_OPERATION_TOUCHES_DATA_STORE",
            GraphEdgeKind::FindingHasEvidence => "FINDING_HAS_EVIDENCE",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "REPO_HAS_FILE" => Some(GraphEdgeKind::RepoHasFile),
            "FILE_HAS_VERSION" => Some(GraphEdgeKind::FileHasVersion),
            "FILE_DEFINES_MODULE" => Some(GraphEdgeKind::FileDefinesModule),
            "FILE_HAS_ROLE" => Some(GraphEdgeKind::FileHasRole),
            "FILE_CONTAINS_SYMBOL" => Some(GraphEdgeKind::FileContainsSymbol),
            "MODULE_IMPORTS_MODULE" => Some(GraphEdgeKind::ModuleImportsModule),
            "IMPORT_DECL_REFERENCES_MODULE" => Some(GraphEdgeKind::ImportDeclReferencesModule),
            "IMPORT_RESOLVES_TO_MODULE" => Some(GraphEdgeKind::ImportResolvesToModule),
            "IMPORT_RESOLVES_TO_SYMBOL" => Some(GraphEdgeKind::ImportResolvesToSymbol),
            "MODULE_EXPORTS_SYMBOL" => Some(GraphEdgeKind::ModuleExportsSymbol),
            "ROUTE_DECLARED_IN_FILE" => Some(GraphEdgeKind::RouteDeclaredInFile),
            "ROUTE_HANDLED_BY_SYMBOL" => Some(GraphEdgeKind::RouteHandledBySymbol),
            "ROUTE_HAS_ENDPOINT" => Some(GraphEdgeKind::RouteHasEndpoint),
            "MODULE_REEXPORTS_MODULE" => Some(GraphEdgeKind::ModuleReexportsModule),
            "REEXPORT_RESOLVES_TO_SYMBOL" => Some(GraphEdgeKind::ReexportResolvesToSymbol),
            "CALLSITE_REFERENCES_SYMBOL" => Some(GraphEdgeKind::CallsiteReferencesSymbol),
            "DATA_OPERATION_READS_DATA_STORE" => Some(GraphEdgeKind::DataOperationReadsDataStore),
            "DATA_OPERATION_WRITES_DATA_STORE" => Some(GraphEdgeKind::DataOperationWritesDataStore),
            "DATA_OPERATION_DELETES_DATA_STORE" => {
                Some(GraphEdgeKind::DataOperationDeletesDataStore)
            }
            "DATA_OPERATION_TOUCHES_DATA_STORE" => {
                Some(GraphEdgeKind::DataOperationTouchesDataStore)
            }
            "FINDING_HAS_EVIDENCE" => Some(GraphEdgeKind::FindingHasEvidence),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for GraphEdgeKind {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for GraphEdgeKind {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for GraphEdgeKind {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        GraphEdgeKind::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown graph_edge_kind \"{raw}\": this engine and its caller disagree about the graph_edge_kind vocabulary"
            ))
        })
    }
}

/// Roles a file can be detected as. Crosses the boundary inside `file_role_detected` facts, `file_role` graph nodes, convention matchers (`applies_to_file_roles`) and the MCP get_repo_map filter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum FileRole {
    ApiRoute,
    ServerModule,
    ServiceModule,
    DataAccessModule,
    Component,
    UiComponent,
    HookModule,
    SchemaModule,
    Test,
    Config,
    CliCommandModule,
    CoreModule,
    QueryModule,
    FactgraphModule,
    AdapterModule,
    StorageModule,
    EngineBridgeModule,
    McpModule,
    Docs,
    PackageManifest,
    Custom,
}

impl FileRole {
    /// Every member, in manifest order.
    pub const ALL: &'static [FileRole] = &[
        FileRole::ApiRoute,
        FileRole::ServerModule,
        FileRole::ServiceModule,
        FileRole::DataAccessModule,
        FileRole::Component,
        FileRole::UiComponent,
        FileRole::HookModule,
        FileRole::SchemaModule,
        FileRole::Test,
        FileRole::Config,
        FileRole::CliCommandModule,
        FileRole::CoreModule,
        FileRole::QueryModule,
        FileRole::FactgraphModule,
        FileRole::AdapterModule,
        FileRole::StorageModule,
        FileRole::EngineBridgeModule,
        FileRole::McpModule,
        FileRole::Docs,
        FileRole::PackageManifest,
        FileRole::Custom,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            FileRole::ApiRoute => "api_route",
            FileRole::ServerModule => "server_module",
            FileRole::ServiceModule => "service_module",
            FileRole::DataAccessModule => "data_access_module",
            FileRole::Component => "component",
            FileRole::UiComponent => "ui_component",
            FileRole::HookModule => "hook_module",
            FileRole::SchemaModule => "schema_module",
            FileRole::Test => "test",
            FileRole::Config => "config",
            FileRole::CliCommandModule => "cli_command_module",
            FileRole::CoreModule => "core_module",
            FileRole::QueryModule => "query_module",
            FileRole::FactgraphModule => "factgraph_module",
            FileRole::AdapterModule => "adapter_module",
            FileRole::StorageModule => "storage_module",
            FileRole::EngineBridgeModule => "engine_bridge_module",
            FileRole::McpModule => "mcp_module",
            FileRole::Docs => "docs",
            FileRole::PackageManifest => "package_manifest",
            FileRole::Custom => "custom",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "api_route" => Some(FileRole::ApiRoute),
            "server_module" => Some(FileRole::ServerModule),
            "service_module" => Some(FileRole::ServiceModule),
            "data_access_module" => Some(FileRole::DataAccessModule),
            "component" => Some(FileRole::Component),
            "ui_component" => Some(FileRole::UiComponent),
            "hook_module" => Some(FileRole::HookModule),
            "schema_module" => Some(FileRole::SchemaModule),
            "test" => Some(FileRole::Test),
            "config" => Some(FileRole::Config),
            "cli_command_module" => Some(FileRole::CliCommandModule),
            "core_module" => Some(FileRole::CoreModule),
            "query_module" => Some(FileRole::QueryModule),
            "factgraph_module" => Some(FileRole::FactgraphModule),
            "adapter_module" => Some(FileRole::AdapterModule),
            "storage_module" => Some(FileRole::StorageModule),
            "engine_bridge_module" => Some(FileRole::EngineBridgeModule),
            "mcp_module" => Some(FileRole::McpModule),
            "docs" => Some(FileRole::Docs),
            "package_manifest" => Some(FileRole::PackageManifest),
            "custom" => Some(FileRole::Custom),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for FileRole {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for FileRole {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for FileRole {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        FileRole::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown file_role \"{raw}\": this engine and its caller disagree about the file_role vocabulary"
            ))
        })
    }
}

/// CV-2: what kind of caller a route serves. Conditions convention scope (`applies_to_route_flavors`) and carried across the boundary in `route_flavor_detected` facts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RouteFlavor {
    ApiRoute,
    CronJob,
    WebhookHandler,
}

impl RouteFlavor {
    /// Every member, in manifest order.
    pub const ALL: &'static [RouteFlavor] = &[
        RouteFlavor::ApiRoute,
        RouteFlavor::CronJob,
        RouteFlavor::WebhookHandler,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            RouteFlavor::ApiRoute => "api_route",
            RouteFlavor::CronJob => "cron_job",
            RouteFlavor::WebhookHandler => "webhook_handler",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "api_route" => Some(RouteFlavor::ApiRoute),
            "cron_job" => Some(RouteFlavor::CronJob),
            "webhook_handler" => Some(RouteFlavor::WebhookHandler),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for RouteFlavor {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for RouteFlavor {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for RouteFlavor {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        RouteFlavor::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown route_flavor \"{raw}\": this engine and its caller disagree about the route_flavor vocabulary"
            ))
        })
    }
}

/// D-P3a: every convention kind, and where each one dispatches.
///
/// The 23 kinds were evaluated by three mechanisms - a literal-match chain in check_command.rs, the
/// is_phase6_security_convention predicate beside it, and a separate chain in the CLI's run-check.ts -
/// with three more accepted by the schema and implemented nowhere. No single place listed all of them,
/// so a 24th kind with no evaluator would have been caught by nothing: `check` returns a clean pass for
/// a contract that enforces nothing.
///
/// `dispatch` is now that place. The generated Rust ConventionDispatch is matched exhaustively by the
/// engine, so a new kind that names no target does not compile.
///
/// dispatch values:
///   engine_direct - a dedicated arm in crates/drift-engine/src/check_command.rs
///   engine_phase6 - the shared Phase 6 evaluator in the same file
///   cli           - an arm in packages/cli/src/check/run-check.ts
///   none          - accepted by the schema, implemented by neither (UNIMPLEMENTED_CONVENTION_KINDS)
///
/// `proposable` marks the kinds candidate inference can propose. It is exactly the set the engine's
/// candidate payload used to declare in its own hand-written enum.
///
/// `security_contract` marks the kinds that carry a security boundary proof. Three lists claimed
/// to be this set and two of them agreed: SecurityContractKindSchema (13) and
/// EngineSecurityContractKindSchema (13) against EXPERIMENTAL_SECURITY_CONVENTION_KINDS (12),
/// which omitted api_route_forbids_secret_exposure - the flag that keeps every security kind
/// behind --experimental-security, missing the one kind whose whole subject is secrets.
///
/// `requires_engine_source` marks the kinds whose engine evaluator re-reads the route file from
/// disk instead of working from the facts on the wire. All twelve security kinds do. Without
/// `repo_root` - which the wire protocol declares Option<String> - every one of them silently
/// produced nothing, and `check` reported a clean pass. See D-F1 in check_command.rs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ConventionKind {
    ApiRouteNoDirectDataAccess,
    ApiRouteRequiresServiceDelegation,
    ApiRouteRequiresAuthHelper,
    MiddlewareMustCoverRoutes,
    ApiRouteRequiresRequestValidation,
    ApiRouteForbidsUntrustedSsrf,
    ApiRouteForbidsRawSqlWithoutParams,
    ApiRouteCorsMustMatchPolicy,
    ApiRouteRequiresCsrfForMutation,
    ApiRouteRequiresRateLimit,
    ApiRouteForbidsSensitiveResponseFields,
    ApiRouteForbidsSecretExposure,
    SessionObjectMustComeFromTrustedHelper,
    ApiRouteRequiresAuthorization,
    ApiRouteRequiresTenantScope,
    TestExpectedForChangedModule,
    CustomBriefing,
    FileRole,
    ModulePlacement,
    ImportBoundary,
    EntrypointFlow,
    CanonicalHelperReuse,
    RequiredChangeChecks,
}

impl ConventionKind {
    /// Every member, in manifest order.
    pub const ALL: &'static [ConventionKind] = &[
        ConventionKind::ApiRouteNoDirectDataAccess,
        ConventionKind::ApiRouteRequiresServiceDelegation,
        ConventionKind::ApiRouteRequiresAuthHelper,
        ConventionKind::MiddlewareMustCoverRoutes,
        ConventionKind::ApiRouteRequiresRequestValidation,
        ConventionKind::ApiRouteForbidsUntrustedSsrf,
        ConventionKind::ApiRouteForbidsRawSqlWithoutParams,
        ConventionKind::ApiRouteCorsMustMatchPolicy,
        ConventionKind::ApiRouteRequiresCsrfForMutation,
        ConventionKind::ApiRouteRequiresRateLimit,
        ConventionKind::ApiRouteForbidsSensitiveResponseFields,
        ConventionKind::ApiRouteForbidsSecretExposure,
        ConventionKind::SessionObjectMustComeFromTrustedHelper,
        ConventionKind::ApiRouteRequiresAuthorization,
        ConventionKind::ApiRouteRequiresTenantScope,
        ConventionKind::TestExpectedForChangedModule,
        ConventionKind::CustomBriefing,
        ConventionKind::FileRole,
        ConventionKind::ModulePlacement,
        ConventionKind::ImportBoundary,
        ConventionKind::EntrypointFlow,
        ConventionKind::CanonicalHelperReuse,
        ConventionKind::RequiredChangeChecks,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            ConventionKind::ApiRouteNoDirectDataAccess => "api_route_no_direct_data_access",
            ConventionKind::ApiRouteRequiresServiceDelegation => {
                "api_route_requires_service_delegation"
            }
            ConventionKind::ApiRouteRequiresAuthHelper => "api_route_requires_auth_helper",
            ConventionKind::MiddlewareMustCoverRoutes => "middleware_must_cover_routes",
            ConventionKind::ApiRouteRequiresRequestValidation => {
                "api_route_requires_request_validation"
            }
            ConventionKind::ApiRouteForbidsUntrustedSsrf => "api_route_forbids_untrusted_ssrf",
            ConventionKind::ApiRouteForbidsRawSqlWithoutParams => {
                "api_route_forbids_raw_sql_without_params"
            }
            ConventionKind::ApiRouteCorsMustMatchPolicy => "api_route_cors_must_match_policy",
            ConventionKind::ApiRouteRequiresCsrfForMutation => {
                "api_route_requires_csrf_for_mutation"
            }
            ConventionKind::ApiRouteRequiresRateLimit => "api_route_requires_rate_limit",
            ConventionKind::ApiRouteForbidsSensitiveResponseFields => {
                "api_route_forbids_sensitive_response_fields"
            }
            ConventionKind::ApiRouteForbidsSecretExposure => "api_route_forbids_secret_exposure",
            ConventionKind::SessionObjectMustComeFromTrustedHelper => {
                "session_object_must_come_from_trusted_helper"
            }
            ConventionKind::ApiRouteRequiresAuthorization => "api_route_requires_authorization",
            ConventionKind::ApiRouteRequiresTenantScope => "api_route_requires_tenant_scope",
            ConventionKind::TestExpectedForChangedModule => "test_expected_for_changed_module",
            ConventionKind::CustomBriefing => "custom_briefing",
            ConventionKind::FileRole => "file_role",
            ConventionKind::ModulePlacement => "module_placement",
            ConventionKind::ImportBoundary => "import_boundary",
            ConventionKind::EntrypointFlow => "entrypoint_flow",
            ConventionKind::CanonicalHelperReuse => "canonical_helper_reuse",
            ConventionKind::RequiredChangeChecks => "required_change_checks",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "api_route_no_direct_data_access" => Some(ConventionKind::ApiRouteNoDirectDataAccess),
            "api_route_requires_service_delegation" => {
                Some(ConventionKind::ApiRouteRequiresServiceDelegation)
            }
            "api_route_requires_auth_helper" => Some(ConventionKind::ApiRouteRequiresAuthHelper),
            "middleware_must_cover_routes" => Some(ConventionKind::MiddlewareMustCoverRoutes),
            "api_route_requires_request_validation" => {
                Some(ConventionKind::ApiRouteRequiresRequestValidation)
            }
            "api_route_forbids_untrusted_ssrf" => {
                Some(ConventionKind::ApiRouteForbidsUntrustedSsrf)
            }
            "api_route_forbids_raw_sql_without_params" => {
                Some(ConventionKind::ApiRouteForbidsRawSqlWithoutParams)
            }
            "api_route_cors_must_match_policy" => Some(ConventionKind::ApiRouteCorsMustMatchPolicy),
            "api_route_requires_csrf_for_mutation" => {
                Some(ConventionKind::ApiRouteRequiresCsrfForMutation)
            }
            "api_route_requires_rate_limit" => Some(ConventionKind::ApiRouteRequiresRateLimit),
            "api_route_forbids_sensitive_response_fields" => {
                Some(ConventionKind::ApiRouteForbidsSensitiveResponseFields)
            }
            "api_route_forbids_secret_exposure" => {
                Some(ConventionKind::ApiRouteForbidsSecretExposure)
            }
            "session_object_must_come_from_trusted_helper" => {
                Some(ConventionKind::SessionObjectMustComeFromTrustedHelper)
            }
            "api_route_requires_authorization" => {
                Some(ConventionKind::ApiRouteRequiresAuthorization)
            }
            "api_route_requires_tenant_scope" => Some(ConventionKind::ApiRouteRequiresTenantScope),
            "test_expected_for_changed_module" => {
                Some(ConventionKind::TestExpectedForChangedModule)
            }
            "custom_briefing" => Some(ConventionKind::CustomBriefing),
            "file_role" => Some(ConventionKind::FileRole),
            "module_placement" => Some(ConventionKind::ModulePlacement),
            "import_boundary" => Some(ConventionKind::ImportBoundary),
            "entrypoint_flow" => Some(ConventionKind::EntrypointFlow),
            "canonical_helper_reuse" => Some(ConventionKind::CanonicalHelperReuse),
            "required_change_checks" => Some(ConventionKind::RequiredChangeChecks),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for ConventionKind {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for ConventionKind {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for ConventionKind {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        ConventionKind::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown convention_kind \"{raw}\": this engine and its caller disagree about the convention_kind vocabulary"
            ))
        })
    }
}

/// Where a convention kind is evaluated. Exhaustively matched by the engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ConventionDispatch {
    EngineDirect,
    None,
    EnginePhase6,
    Cli,
}

impl ConventionKind {
    /// The evaluator that owns this kind.
    pub fn dispatch(self) -> ConventionDispatch {
        match self {
            ConventionKind::ApiRouteNoDirectDataAccess => ConventionDispatch::EngineDirect,
            ConventionKind::ApiRouteRequiresServiceDelegation => ConventionDispatch::None,
            ConventionKind::ApiRouteRequiresAuthHelper => ConventionDispatch::EngineDirect,
            ConventionKind::MiddlewareMustCoverRoutes => ConventionDispatch::None,
            ConventionKind::ApiRouteRequiresRequestValidation => ConventionDispatch::EngineDirect,
            ConventionKind::ApiRouteForbidsUntrustedSsrf => ConventionDispatch::EnginePhase6,
            ConventionKind::ApiRouteForbidsRawSqlWithoutParams => ConventionDispatch::EnginePhase6,
            ConventionKind::ApiRouteCorsMustMatchPolicy => ConventionDispatch::EnginePhase6,
            ConventionKind::ApiRouteRequiresCsrfForMutation => ConventionDispatch::EnginePhase6,
            ConventionKind::ApiRouteRequiresRateLimit => ConventionDispatch::EnginePhase6,
            ConventionKind::ApiRouteForbidsSensitiveResponseFields => {
                ConventionDispatch::EngineDirect
            }
            ConventionKind::ApiRouteForbidsSecretExposure => ConventionDispatch::EngineDirect,
            ConventionKind::SessionObjectMustComeFromTrustedHelper => {
                ConventionDispatch::EngineDirect
            }
            ConventionKind::ApiRouteRequiresAuthorization => ConventionDispatch::EngineDirect,
            ConventionKind::ApiRouteRequiresTenantScope => ConventionDispatch::EngineDirect,
            ConventionKind::TestExpectedForChangedModule => ConventionDispatch::None,
            ConventionKind::CustomBriefing => ConventionDispatch::None,
            ConventionKind::FileRole => ConventionDispatch::Cli,
            ConventionKind::ModulePlacement => ConventionDispatch::Cli,
            ConventionKind::ImportBoundary => ConventionDispatch::Cli,
            ConventionKind::EntrypointFlow => ConventionDispatch::Cli,
            ConventionKind::CanonicalHelperReuse => ConventionDispatch::Cli,
            ConventionKind::RequiredChangeChecks => ConventionDispatch::Cli,
        }
    }

    /// Whether candidate inference may propose this kind.
    pub fn proposable(self) -> bool {
        match self {
            ConventionKind::ApiRouteNoDirectDataAccess => true,
            ConventionKind::ApiRouteRequiresServiceDelegation => true,
            ConventionKind::ApiRouteRequiresAuthHelper => true,
            ConventionKind::MiddlewareMustCoverRoutes => true,
            ConventionKind::ApiRouteRequiresRequestValidation => true,
            ConventionKind::ApiRouteForbidsUntrustedSsrf => true,
            ConventionKind::ApiRouteForbidsRawSqlWithoutParams => true,
            ConventionKind::ApiRouteCorsMustMatchPolicy => true,
            ConventionKind::ApiRouteRequiresCsrfForMutation => true,
            ConventionKind::ApiRouteRequiresRateLimit => true,
            ConventionKind::ApiRouteForbidsSensitiveResponseFields => true,
            ConventionKind::ApiRouteForbidsSecretExposure => true,
            ConventionKind::SessionObjectMustComeFromTrustedHelper => true,
            ConventionKind::ApiRouteRequiresAuthorization => true,
            ConventionKind::ApiRouteRequiresTenantScope => true,
            ConventionKind::TestExpectedForChangedModule => true,
            ConventionKind::CustomBriefing => true,
            ConventionKind::FileRole => false,
            ConventionKind::ModulePlacement => false,
            ConventionKind::ImportBoundary => false,
            ConventionKind::EntrypointFlow => false,
            ConventionKind::CanonicalHelperReuse => false,
            ConventionKind::RequiredChangeChecks => false,
        }
    }

    /// Whether this kind's engine evaluator re-reads the route file from disk.
    ///
    /// True for every kind whose evaluator calls `read_repo_file`. Such a kind cannot be
    /// evaluated at all without `repo_root`, and `repo_root` is optional on the wire.
    pub fn requires_engine_source(self) -> bool {
        match self {
            ConventionKind::ApiRouteNoDirectDataAccess => false,
            ConventionKind::ApiRouteRequiresServiceDelegation => false,
            ConventionKind::ApiRouteRequiresAuthHelper => true,
            ConventionKind::MiddlewareMustCoverRoutes => false,
            ConventionKind::ApiRouteRequiresRequestValidation => true,
            ConventionKind::ApiRouteForbidsUntrustedSsrf => true,
            ConventionKind::ApiRouteForbidsRawSqlWithoutParams => true,
            ConventionKind::ApiRouteCorsMustMatchPolicy => true,
            ConventionKind::ApiRouteRequiresCsrfForMutation => true,
            ConventionKind::ApiRouteRequiresRateLimit => true,
            ConventionKind::ApiRouteForbidsSensitiveResponseFields => true,
            ConventionKind::ApiRouteForbidsSecretExposure => true,
            ConventionKind::SessionObjectMustComeFromTrustedHelper => true,
            ConventionKind::ApiRouteRequiresAuthorization => true,
            ConventionKind::ApiRouteRequiresTenantScope => true,
            ConventionKind::TestExpectedForChangedModule => false,
            ConventionKind::CustomBriefing => false,
            ConventionKind::FileRole => false,
            ConventionKind::ModulePlacement => false,
            ConventionKind::ImportBoundary => false,
            ConventionKind::EntrypointFlow => false,
            ConventionKind::CanonicalHelperReuse => false,
            ConventionKind::RequiredChangeChecks => false,
        }
    }
}

/// D-S1: the one capability namespace.
///
/// These ids are what may appear in EngineCapabilityStats (certified/required/missing),
/// EngineCompleteness.{required,missing}_capabilities, and therefore in ScanCapabilityReport and the
/// semantic coverage contract built from it.
///
/// There used to be two namespaces with zero string overlap BY CONSTRUCTION: the engine emitted bare
/// names (`graph_stream`, `route_detection`) and BUILTIN_SEMANTIC_CAPABILITIES declared eight ids of
/// the form `ts.<name>.v1`. A hand-written translation table in packages/query/src/semantic-coverage.ts
/// was supposed to bridge them and named four capabilities the engine has never emitted
/// (`data_operations`, `data_operation_facts`, `fact_graph`, `route_flow`).
///
/// The bare namespace won because it is the one on the wire: nine of the eleven sites that PRODUCE a
/// capability id already emitted bare names (both Rust capability_stats call sites, repo_completeness,
/// check_command's fourteen security labels, candidate_command, run-check.ts, convention-candidates.ts,
/// factgraph's two completeness entries, the TypeScript fallback's degraded list). The `ts.*.v1`
/// namespace appeared in exactly three places - the contract list itself and the two
/// DEFAULT_PREFLIGHT_CAPABILITIES references - none of which produced wire data.
///
/// `engine_certified` marks the members crates/drift-engine/src/protocol.rs::certified_capabilities()
/// reports. `security` marks the members security_capabilities() reports (D-P3b).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ScanCapability {
    FileDiscovery,
    SyntaxFacts,
    StaticImports,
    ImportResolution,
    SymbolLinking,
    GraphStream,
    RouteDetection,
    RouteFlow,
    DataOperationDetection,
    DirectDataAccessCheck,
    CandidateInference,
    SecurityFacts,
    AuthBoundaryFacts,
    ControlFlowGuardDominance,
    MiddlewareCoverage,
    RequestValidationFacts,
    OutboundRequestFacts,
    RawSqlFacts,
    CorsPolicyFacts,
    CsrfFacts,
    RateLimitFacts,
    ResponseShapeFacts,
    SecretExposure,
    SessionTrust,
    Authorization,
    TenantScope,
    DataAccessInference,
    DynamicImports,
    ComputedCalls,
    Graph,
    GraphEvidence,
    DeterministicEnforcement,
}

impl ScanCapability {
    /// Every member, in manifest order.
    pub const ALL: &'static [ScanCapability] = &[
        ScanCapability::FileDiscovery,
        ScanCapability::SyntaxFacts,
        ScanCapability::StaticImports,
        ScanCapability::ImportResolution,
        ScanCapability::SymbolLinking,
        ScanCapability::GraphStream,
        ScanCapability::RouteDetection,
        ScanCapability::RouteFlow,
        ScanCapability::DataOperationDetection,
        ScanCapability::DirectDataAccessCheck,
        ScanCapability::CandidateInference,
        ScanCapability::SecurityFacts,
        ScanCapability::AuthBoundaryFacts,
        ScanCapability::ControlFlowGuardDominance,
        ScanCapability::MiddlewareCoverage,
        ScanCapability::RequestValidationFacts,
        ScanCapability::OutboundRequestFacts,
        ScanCapability::RawSqlFacts,
        ScanCapability::CorsPolicyFacts,
        ScanCapability::CsrfFacts,
        ScanCapability::RateLimitFacts,
        ScanCapability::ResponseShapeFacts,
        ScanCapability::SecretExposure,
        ScanCapability::SessionTrust,
        ScanCapability::Authorization,
        ScanCapability::TenantScope,
        ScanCapability::DataAccessInference,
        ScanCapability::DynamicImports,
        ScanCapability::ComputedCalls,
        ScanCapability::Graph,
        ScanCapability::GraphEvidence,
        ScanCapability::DeterministicEnforcement,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            ScanCapability::FileDiscovery => "file_discovery",
            ScanCapability::SyntaxFacts => "syntax_facts",
            ScanCapability::StaticImports => "static_imports",
            ScanCapability::ImportResolution => "import_resolution",
            ScanCapability::SymbolLinking => "symbol_linking",
            ScanCapability::GraphStream => "graph_stream",
            ScanCapability::RouteDetection => "route_detection",
            ScanCapability::RouteFlow => "route_flow",
            ScanCapability::DataOperationDetection => "data_operation_detection",
            ScanCapability::DirectDataAccessCheck => "direct_data_access_check",
            ScanCapability::CandidateInference => "candidate_inference",
            ScanCapability::SecurityFacts => "security_facts",
            ScanCapability::AuthBoundaryFacts => "auth_boundary_facts",
            ScanCapability::ControlFlowGuardDominance => "control_flow_guard_dominance",
            ScanCapability::MiddlewareCoverage => "middleware_coverage",
            ScanCapability::RequestValidationFacts => "request_validation_facts",
            ScanCapability::OutboundRequestFacts => "outbound_request_facts",
            ScanCapability::RawSqlFacts => "raw_sql_facts",
            ScanCapability::CorsPolicyFacts => "cors_policy_facts",
            ScanCapability::CsrfFacts => "csrf_facts",
            ScanCapability::RateLimitFacts => "rate_limit_facts",
            ScanCapability::ResponseShapeFacts => "response_shape_facts",
            ScanCapability::SecretExposure => "secret_exposure",
            ScanCapability::SessionTrust => "session_trust",
            ScanCapability::Authorization => "authorization",
            ScanCapability::TenantScope => "tenant_scope",
            ScanCapability::DataAccessInference => "data_access_inference",
            ScanCapability::DynamicImports => "dynamic_imports",
            ScanCapability::ComputedCalls => "computed_calls",
            ScanCapability::Graph => "graph",
            ScanCapability::GraphEvidence => "graph_evidence",
            ScanCapability::DeterministicEnforcement => "deterministic_enforcement",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "file_discovery" => Some(ScanCapability::FileDiscovery),
            "syntax_facts" => Some(ScanCapability::SyntaxFacts),
            "static_imports" => Some(ScanCapability::StaticImports),
            "import_resolution" => Some(ScanCapability::ImportResolution),
            "symbol_linking" => Some(ScanCapability::SymbolLinking),
            "graph_stream" => Some(ScanCapability::GraphStream),
            "route_detection" => Some(ScanCapability::RouteDetection),
            "route_flow" => Some(ScanCapability::RouteFlow),
            "data_operation_detection" => Some(ScanCapability::DataOperationDetection),
            "direct_data_access_check" => Some(ScanCapability::DirectDataAccessCheck),
            "candidate_inference" => Some(ScanCapability::CandidateInference),
            "security_facts" => Some(ScanCapability::SecurityFacts),
            "auth_boundary_facts" => Some(ScanCapability::AuthBoundaryFacts),
            "control_flow_guard_dominance" => Some(ScanCapability::ControlFlowGuardDominance),
            "middleware_coverage" => Some(ScanCapability::MiddlewareCoverage),
            "request_validation_facts" => Some(ScanCapability::RequestValidationFacts),
            "outbound_request_facts" => Some(ScanCapability::OutboundRequestFacts),
            "raw_sql_facts" => Some(ScanCapability::RawSqlFacts),
            "cors_policy_facts" => Some(ScanCapability::CorsPolicyFacts),
            "csrf_facts" => Some(ScanCapability::CsrfFacts),
            "rate_limit_facts" => Some(ScanCapability::RateLimitFacts),
            "response_shape_facts" => Some(ScanCapability::ResponseShapeFacts),
            "secret_exposure" => Some(ScanCapability::SecretExposure),
            "session_trust" => Some(ScanCapability::SessionTrust),
            "authorization" => Some(ScanCapability::Authorization),
            "tenant_scope" => Some(ScanCapability::TenantScope),
            "data_access_inference" => Some(ScanCapability::DataAccessInference),
            "dynamic_imports" => Some(ScanCapability::DynamicImports),
            "computed_calls" => Some(ScanCapability::ComputedCalls),
            "graph" => Some(ScanCapability::Graph),
            "graph_evidence" => Some(ScanCapability::GraphEvidence),
            "deterministic_enforcement" => Some(ScanCapability::DeterministicEnforcement),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for ScanCapability {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for ScanCapability {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for ScanCapability {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        ScanCapability::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown scan_capability \"{raw}\": this engine and its caller disagree about the scan_capability vocabulary"
            ))
        })
    }
}

impl ScanCapability {
    /// The capabilities crates/drift-engine reports as certified.
    pub const ENGINE_CERTIFIED: &'static [ScanCapability] = &[
        ScanCapability::FileDiscovery,
        ScanCapability::SyntaxFacts,
        ScanCapability::StaticImports,
        ScanCapability::ImportResolution,
        ScanCapability::SymbolLinking,
        ScanCapability::GraphStream,
        ScanCapability::RouteDetection,
        ScanCapability::RouteFlow,
        ScanCapability::DataOperationDetection,
        ScanCapability::DirectDataAccessCheck,
        ScanCapability::CandidateInference,
        ScanCapability::SecurityFacts,
        ScanCapability::AuthBoundaryFacts,
        ScanCapability::ControlFlowGuardDominance,
    ];

    /// The capabilities the security layer reports on (D-P3b).
    pub const SECURITY: &'static [ScanCapability] = &[
        ScanCapability::SecurityFacts,
        ScanCapability::AuthBoundaryFacts,
        ScanCapability::ControlFlowGuardDominance,
        ScanCapability::MiddlewareCoverage,
        ScanCapability::RequestValidationFacts,
        ScanCapability::OutboundRequestFacts,
        ScanCapability::RawSqlFacts,
        ScanCapability::CorsPolicyFacts,
        ScanCapability::CsrfFacts,
        ScanCapability::RateLimitFacts,
        ScanCapability::ResponseShapeFacts,
        ScanCapability::SecretExposure,
        ScanCapability::SessionTrust,
        ScanCapability::Authorization,
        ScanCapability::TenantScope,
    ];
}

/// Why a session object could not be proven trusted. PROOF-LEVEL vocabulary: it says why the proof failed. The FINDING-level code a user sees (SecurityMissingProofCodeSchema) is separate and is derived from this by the phase4 finding-reason mapping in check_command.rs. The two are deliberately different vocabularies; mapping between them must be total.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SessionTrustReason {
    DerivedFromRequest,
    UnknownHelper,
    MissingAuthGuard,
    ParserGap,
}

impl SessionTrustReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [SessionTrustReason] = &[
        SessionTrustReason::DerivedFromRequest,
        SessionTrustReason::UnknownHelper,
        SessionTrustReason::MissingAuthGuard,
        SessionTrustReason::ParserGap,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            SessionTrustReason::DerivedFromRequest => "derived_from_request",
            SessionTrustReason::UnknownHelper => "unknown_helper",
            SessionTrustReason::MissingAuthGuard => "missing_auth_guard",
            SessionTrustReason::ParserGap => "parser_gap",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "derived_from_request" => Some(SessionTrustReason::DerivedFromRequest),
            "unknown_helper" => Some(SessionTrustReason::UnknownHelper),
            "missing_auth_guard" => Some(SessionTrustReason::MissingAuthGuard),
            "parser_gap" => Some(SessionTrustReason::ParserGap),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for SessionTrustReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for SessionTrustReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for SessionTrustReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        SessionTrustReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown session_trust_reason \"{raw}\": this engine and its caller disagree about the session_trust_reason vocabulary"
            ))
        })
    }
}

/// Why an authorization proof could not be completed. PROOF-LEVEL vocabulary, on `authorization.missing[].reason`. The list carries two spellings of the same three concepts - an older `no_authorization_guard`/`guard_not_dominating_sink` pair and the newer `authorization_guard_missing`/`authorization_guard_not_dominating_sink` - because the enum was WIDENED rather than migrated when the engine's wording changed. Only the newer spelling has a producer today; the older one is reserved, because the schema is applied on read and stored rows may still hold it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AuthorizationMissingReason {
    NoAuthorizationGuard,
    GuardNotDominatingSink,
    UnknownPolicyHelper,
    SessionNotTrusted,
    AuthorizationGuardMissing,
    AuthorizationGuardNotDominatingSink,
}

impl AuthorizationMissingReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [AuthorizationMissingReason] = &[
        AuthorizationMissingReason::NoAuthorizationGuard,
        AuthorizationMissingReason::GuardNotDominatingSink,
        AuthorizationMissingReason::UnknownPolicyHelper,
        AuthorizationMissingReason::SessionNotTrusted,
        AuthorizationMissingReason::AuthorizationGuardMissing,
        AuthorizationMissingReason::AuthorizationGuardNotDominatingSink,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            AuthorizationMissingReason::NoAuthorizationGuard => "no_authorization_guard",
            AuthorizationMissingReason::GuardNotDominatingSink => "guard_not_dominating_sink",
            AuthorizationMissingReason::UnknownPolicyHelper => "unknown_policy_helper",
            AuthorizationMissingReason::SessionNotTrusted => "session_not_trusted",
            AuthorizationMissingReason::AuthorizationGuardMissing => "authorization_guard_missing",
            AuthorizationMissingReason::AuthorizationGuardNotDominatingSink => {
                "authorization_guard_not_dominating_sink"
            }
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "no_authorization_guard" => Some(AuthorizationMissingReason::NoAuthorizationGuard),
            "guard_not_dominating_sink" => Some(AuthorizationMissingReason::GuardNotDominatingSink),
            "unknown_policy_helper" => Some(AuthorizationMissingReason::UnknownPolicyHelper),
            "session_not_trusted" => Some(AuthorizationMissingReason::SessionNotTrusted),
            "authorization_guard_missing" => {
                Some(AuthorizationMissingReason::AuthorizationGuardMissing)
            }
            "authorization_guard_not_dominating_sink" => {
                Some(AuthorizationMissingReason::AuthorizationGuardNotDominatingSink)
            }
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for AuthorizationMissingReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for AuthorizationMissingReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for AuthorizationMissingReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        AuthorizationMissingReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown authorization_missing_reason \"{raw}\": this engine and its caller disagree about the authorization_missing_reason vocabulary"
            ))
        })
    }
}

/// Why a tenant-scope proof could not be completed. PROOF-LEVEL vocabulary, on `tenant.missing[].reason`. Widened the same way authorization_missing_reason was: the first three members are the spelling the original design named, the last three are the spelling the engine emits, and `parser_gap` is a fourth concept with no producer at all. Only the newer three are constructed; the rest are reserved rather than deleted, because the schema is applied on read.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TenantMissingReason {
    NoTenantPredicate,
    UntrustedTenantSource,
    PredicateNotBoundToQuery,
    ParserGap,
    TenantPredicateMissing,
    TenantSourceUntrusted,
    TenantPredicateNotBoundToQuery,
}

impl TenantMissingReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [TenantMissingReason] = &[
        TenantMissingReason::NoTenantPredicate,
        TenantMissingReason::UntrustedTenantSource,
        TenantMissingReason::PredicateNotBoundToQuery,
        TenantMissingReason::ParserGap,
        TenantMissingReason::TenantPredicateMissing,
        TenantMissingReason::TenantSourceUntrusted,
        TenantMissingReason::TenantPredicateNotBoundToQuery,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            TenantMissingReason::NoTenantPredicate => "no_tenant_predicate",
            TenantMissingReason::UntrustedTenantSource => "untrusted_tenant_source",
            TenantMissingReason::PredicateNotBoundToQuery => "predicate_not_bound_to_query",
            TenantMissingReason::ParserGap => "parser_gap",
            TenantMissingReason::TenantPredicateMissing => "tenant_predicate_missing",
            TenantMissingReason::TenantSourceUntrusted => "tenant_source_untrusted",
            TenantMissingReason::TenantPredicateNotBoundToQuery => {
                "tenant_predicate_not_bound_to_query"
            }
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "no_tenant_predicate" => Some(TenantMissingReason::NoTenantPredicate),
            "untrusted_tenant_source" => Some(TenantMissingReason::UntrustedTenantSource),
            "predicate_not_bound_to_query" => Some(TenantMissingReason::PredicateNotBoundToQuery),
            "parser_gap" => Some(TenantMissingReason::ParserGap),
            "tenant_predicate_missing" => Some(TenantMissingReason::TenantPredicateMissing),
            "tenant_source_untrusted" => Some(TenantMissingReason::TenantSourceUntrusted),
            "tenant_predicate_not_bound_to_query" => {
                Some(TenantMissingReason::TenantPredicateNotBoundToQuery)
            }
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for TenantMissingReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for TenantMissingReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for TenantMissingReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        TenantMissingReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown tenant_missing_reason \"{raw}\": this engine and its caller disagree about the tenant_missing_reason vocabulary"
            ))
        })
    }
}

/// Why an auth guard does not dominate a sink. PROOF-LEVEL vocabulary, on `auth.undominated_sinks[].reason`. Unlike the other proof reason vocabularies this one has TWO producers: the straight-line and dynamic-control-flow cases are decided in security_proof.rs, and the path-sensitive ones - a guard in only one branch, a guard behind a callback boundary - in security_control_flow.rs. Every member is produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum UndominatedSinkReason {
    GuardAfterSink,
    GuardOnlyInOneBranch,
    CallbackBoundary,
    UnsupportedDynamicControlFlow,
    NoGuardCall,
}

impl UndominatedSinkReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [UndominatedSinkReason] = &[
        UndominatedSinkReason::GuardAfterSink,
        UndominatedSinkReason::GuardOnlyInOneBranch,
        UndominatedSinkReason::CallbackBoundary,
        UndominatedSinkReason::UnsupportedDynamicControlFlow,
        UndominatedSinkReason::NoGuardCall,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            UndominatedSinkReason::GuardAfterSink => "guard_after_sink",
            UndominatedSinkReason::GuardOnlyInOneBranch => "guard_only_in_one_branch",
            UndominatedSinkReason::CallbackBoundary => "callback_boundary",
            UndominatedSinkReason::UnsupportedDynamicControlFlow => {
                "unsupported_dynamic_control_flow"
            }
            UndominatedSinkReason::NoGuardCall => "no_guard_call",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "guard_after_sink" => Some(UndominatedSinkReason::GuardAfterSink),
            "guard_only_in_one_branch" => Some(UndominatedSinkReason::GuardOnlyInOneBranch),
            "callback_boundary" => Some(UndominatedSinkReason::CallbackBoundary),
            "unsupported_dynamic_control_flow" => {
                Some(UndominatedSinkReason::UnsupportedDynamicControlFlow)
            }
            "no_guard_call" => Some(UndominatedSinkReason::NoGuardCall),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for UndominatedSinkReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for UndominatedSinkReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for UndominatedSinkReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        UndominatedSinkReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown undominated_sink_reason \"{raw}\": this engine and its caller disagree about the undominated_sink_reason vocabulary"
            ))
        })
    }
}

/// Why a middleware does not cover a route. PROOF-LEVEL vocabulary, on `middleware.mismatches[].reason`, produced by static_middleware_coverage in security_control_flow.rs. `dynamic_matcher` has no producer: a dynamic matcher is reported as a parser gap and drives proof_status == ParserGap rather than as a coverage mismatch, so the mismatch spelling of it was declared and never built.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MiddlewareMismatchReason {
    PathNotMatched,
    MethodNotMatched,
    DynamicMatcher,
    UnknownFramework,
}

impl MiddlewareMismatchReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [MiddlewareMismatchReason] = &[
        MiddlewareMismatchReason::PathNotMatched,
        MiddlewareMismatchReason::MethodNotMatched,
        MiddlewareMismatchReason::DynamicMatcher,
        MiddlewareMismatchReason::UnknownFramework,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            MiddlewareMismatchReason::PathNotMatched => "path_not_matched",
            MiddlewareMismatchReason::MethodNotMatched => "method_not_matched",
            MiddlewareMismatchReason::DynamicMatcher => "dynamic_matcher",
            MiddlewareMismatchReason::UnknownFramework => "unknown_framework",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "path_not_matched" => Some(MiddlewareMismatchReason::PathNotMatched),
            "method_not_matched" => Some(MiddlewareMismatchReason::MethodNotMatched),
            "dynamic_matcher" => Some(MiddlewareMismatchReason::DynamicMatcher),
            "unknown_framework" => Some(MiddlewareMismatchReason::UnknownFramework),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for MiddlewareMismatchReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for MiddlewareMismatchReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for MiddlewareMismatchReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        MiddlewareMismatchReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown middleware_mismatch_reason \"{raw}\": this engine and its caller disagree about the middleware_mismatch_reason vocabulary"
            ))
        })
    }
}

/// Why a request input reaching a sink is not covered by a validation proof. PROOF-LEVEL vocabulary, on `request_validation.unvalidated_uses[].reason`. Every member is produced by request_unvalidated_uses in security_proof.rs, and all three are also members of the finding-level SecurityMissingProofCodeSchema, so the two vocabularies agree here and need no bridge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RequestUnvalidatedReason {
    RequestInputNotValidated,
    ValidationResultNotUsed,
    UnknownValidator,
}

impl RequestUnvalidatedReason {
    /// Every member, in manifest order.
    pub const ALL: &'static [RequestUnvalidatedReason] = &[
        RequestUnvalidatedReason::RequestInputNotValidated,
        RequestUnvalidatedReason::ValidationResultNotUsed,
        RequestUnvalidatedReason::UnknownValidator,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            RequestUnvalidatedReason::RequestInputNotValidated => "request_input_not_validated",
            RequestUnvalidatedReason::ValidationResultNotUsed => "validation_result_not_used",
            RequestUnvalidatedReason::UnknownValidator => "unknown_validator",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "request_input_not_validated" => {
                Some(RequestUnvalidatedReason::RequestInputNotValidated)
            }
            "validation_result_not_used" => Some(RequestUnvalidatedReason::ValidationResultNotUsed),
            "unknown_validator" => Some(RequestUnvalidatedReason::UnknownValidator),
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for RequestUnvalidatedReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for RequestUnvalidatedReason {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for RequestUnvalidatedReason {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        RequestUnvalidatedReason::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown request_unvalidated_reason \"{raw}\": this engine and its caller disagree about the request_unvalidated_reason vocabulary"
            ))
        })
    }
}

/// Why a SECURITY proof could not be completed because a construct could not be analysed. Carried on `parser_gaps[].code` inside a security boundary proof, and produced by build_phase4_security_proof, the phase5/phase6 builders and phase4_parser_gap.
///
/// NOT the same vocabulary as `parser_gap_kind`, despite the name. That one is the repo-wide taxonomy of why a REGION of the repo could not be understood - unresolved_import, parser_error, partial_parse - derived CLI-side from engine diagnostic codes and named by the semantic capability contracts. This one is the set of specific TypeScript constructs a security proof gives up on. The two lists are disjoint and the collision is in the English word `parser gap`, not in the concept; merging them would put `unresolved_import` where a security proof expects `unsupported_request_input_spread`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SecurityParserGapCode {
    RouteBindingUnresolved,
    HandlerUnresolved,
    UnsupportedDynamicControlFlow,
    UnsupportedDynamicMiddlewareMatcher,
    UnsupportedRequestInputSpread,
    UnsupportedRequestInputDestructure,
    UnsupportedDynamicOutboundUrl,
    UnsupportedDynamicCorsOrigin,
    DynamicResponseShape,
    UnsupportedDestructuringOrSpread,
    UnsupportedTenantDynamicProperty,
    UnsupportedTenantQueryObjectAlias,
    UnsupportedSessionNestedDestructure,
    UnsupportedCallbackBoundary,
}

impl SecurityParserGapCode {
    /// Every member, in manifest order.
    pub const ALL: &'static [SecurityParserGapCode] = &[
        SecurityParserGapCode::RouteBindingUnresolved,
        SecurityParserGapCode::HandlerUnresolved,
        SecurityParserGapCode::UnsupportedDynamicControlFlow,
        SecurityParserGapCode::UnsupportedDynamicMiddlewareMatcher,
        SecurityParserGapCode::UnsupportedRequestInputSpread,
        SecurityParserGapCode::UnsupportedRequestInputDestructure,
        SecurityParserGapCode::UnsupportedDynamicOutboundUrl,
        SecurityParserGapCode::UnsupportedDynamicCorsOrigin,
        SecurityParserGapCode::DynamicResponseShape,
        SecurityParserGapCode::UnsupportedDestructuringOrSpread,
        SecurityParserGapCode::UnsupportedTenantDynamicProperty,
        SecurityParserGapCode::UnsupportedTenantQueryObjectAlias,
        SecurityParserGapCode::UnsupportedSessionNestedDestructure,
        SecurityParserGapCode::UnsupportedCallbackBoundary,
    ];

    /// The string this member takes on the wire.
    pub fn as_wire(self) -> &'static str {
        match self {
            SecurityParserGapCode::RouteBindingUnresolved => "route_binding_unresolved",
            SecurityParserGapCode::HandlerUnresolved => "handler_unresolved",
            SecurityParserGapCode::UnsupportedDynamicControlFlow => {
                "unsupported_dynamic_control_flow"
            }
            SecurityParserGapCode::UnsupportedDynamicMiddlewareMatcher => {
                "unsupported_dynamic_middleware_matcher"
            }
            SecurityParserGapCode::UnsupportedRequestInputSpread => {
                "unsupported_request_input_spread"
            }
            SecurityParserGapCode::UnsupportedRequestInputDestructure => {
                "unsupported_request_input_destructure"
            }
            SecurityParserGapCode::UnsupportedDynamicOutboundUrl => {
                "unsupported_dynamic_outbound_url"
            }
            SecurityParserGapCode::UnsupportedDynamicCorsOrigin => {
                "unsupported_dynamic_cors_origin"
            }
            SecurityParserGapCode::DynamicResponseShape => "dynamic_response_shape",
            SecurityParserGapCode::UnsupportedDestructuringOrSpread => {
                "unsupported_destructuring_or_spread"
            }
            SecurityParserGapCode::UnsupportedTenantDynamicProperty => {
                "unsupported_tenant_dynamic_property"
            }
            SecurityParserGapCode::UnsupportedTenantQueryObjectAlias => {
                "unsupported_tenant_query_object_alias"
            }
            SecurityParserGapCode::UnsupportedSessionNestedDestructure => {
                "unsupported_session_nested_destructure"
            }
            SecurityParserGapCode::UnsupportedCallbackBoundary => "unsupported_callback_boundary",
        }
    }

    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "route_binding_unresolved" => Some(SecurityParserGapCode::RouteBindingUnresolved),
            "handler_unresolved" => Some(SecurityParserGapCode::HandlerUnresolved),
            "unsupported_dynamic_control_flow" => {
                Some(SecurityParserGapCode::UnsupportedDynamicControlFlow)
            }
            "unsupported_dynamic_middleware_matcher" => {
                Some(SecurityParserGapCode::UnsupportedDynamicMiddlewareMatcher)
            }
            "unsupported_request_input_spread" => {
                Some(SecurityParserGapCode::UnsupportedRequestInputSpread)
            }
            "unsupported_request_input_destructure" => {
                Some(SecurityParserGapCode::UnsupportedRequestInputDestructure)
            }
            "unsupported_dynamic_outbound_url" => {
                Some(SecurityParserGapCode::UnsupportedDynamicOutboundUrl)
            }
            "unsupported_dynamic_cors_origin" => {
                Some(SecurityParserGapCode::UnsupportedDynamicCorsOrigin)
            }
            "dynamic_response_shape" => Some(SecurityParserGapCode::DynamicResponseShape),
            "unsupported_destructuring_or_spread" => {
                Some(SecurityParserGapCode::UnsupportedDestructuringOrSpread)
            }
            "unsupported_tenant_dynamic_property" => {
                Some(SecurityParserGapCode::UnsupportedTenantDynamicProperty)
            }
            "unsupported_tenant_query_object_alias" => {
                Some(SecurityParserGapCode::UnsupportedTenantQueryObjectAlias)
            }
            "unsupported_session_nested_destructure" => {
                Some(SecurityParserGapCode::UnsupportedSessionNestedDestructure)
            }
            "unsupported_callback_boundary" => {
                Some(SecurityParserGapCode::UnsupportedCallbackBoundary)
            }
            _ => None,
        }
    }

    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.
    pub fn all_wire_names() -> Vec<String> {
        let mut names: Vec<String> = Self::ALL
            .iter()
            .map(|member| member.as_wire().to_string())
            .collect();
        names.sort();
        names
    }
}

impl std::fmt::Display for SecurityParserGapCode {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_wire())
    }
}

impl serde::Serialize for SecurityParserGapCode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for SecurityParserGapCode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        SecurityParserGapCode::from_wire(&raw).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "unknown security_parser_gap_code \"{raw}\": this engine and its caller disagree about the security_parser_gap_code vocabulary"
            ))
        })
    }
}
