// @generated by vocabulary/generate.mjs from vocabulary/vocabulary.json. DO NOT EDIT.
//
// Run `node vocabulary/generate.mjs` after changing the manifest.
// scripts/vocabulary-parity.mjs fails when this file and the manifest disagree.

import { z } from "zod";

/**
 * Every fact kind the engine can emit. Declared to the CLI in the `scan_started` handshake so an incompatible pairing is refused before any fact is ingested.
 */
export const FACT_KINDS = [
  "file_detected",
  "import_used",
  "re_export_used",
  "exported_symbol",
  "symbol_called",
  "data_operation_detected",
  "route_declared",
  "file_role_detected",
  "route_flavor_detected",
  "test_declared",
  "auth_guard_called",
  "route_returns_response",
  "callback_boundary_detected",
  "middleware_declared",
  "middleware_matcher_declared",
  "middleware_protects_route",
  "request_input_read",
  "session_read",
  "tenant_source",
  "tenant_guard_called",
  "authorization_guard_called",
  "request_validation_called",
  "validated_input_used",
  "outbound_request_called",
  "raw_sql_called",
  "parameterized_sql_used",
  "csrf_guard_called",
  "rate_limit_guard_called",
  "cors_policy_declared",
  "sensitive_field_declared",
  "response_emits_field",
  "serializer_called",
  "secret_read",
  "data_model_declared",
  "data_model_field_declared",
  "data_model_relation_declared",
] as const;

export const FactKindSchema = z.enum(FACT_KINDS);

export type FactKind = (typeof FACT_KINDS)[number];

/**
 * Node kinds in the fact graph. Part of the `scan_started` handshake alongside fact kinds: before W5 the engine emitted these as bare strings, so a kind the CLI did not know produced a Zod enum failure and exit 1 rather than the exit-3 refusal the handshake exists to give.
 */
export const GRAPH_NODE_KINDS = [
  "repo",
  "package",
  "artifact",
  "file",
  "file_version",
  "module",
  "symbol",
  "import_decl",
  "export_decl",
  "callsite",
  "data_store",
  "data_operation",
  "endpoint",
  "re_export",
  "route",
  "file_role",
  "diagnostic",
  "finding",
] as const;

export const GraphNodeKindSchema = z.enum(GRAPH_NODE_KINDS);

export type GraphNodeKind = (typeof GRAPH_NODE_KINDS)[number];

/**
 * Edge kinds in the fact graph. Same handshake as node kinds.
 */
export const GRAPH_EDGE_KINDS = [
  "REPO_HAS_FILE",
  "FILE_HAS_VERSION",
  "FILE_DEFINES_MODULE",
  "FILE_HAS_ROLE",
  "FILE_CONTAINS_SYMBOL",
  "MODULE_IMPORTS_MODULE",
  "IMPORT_DECL_REFERENCES_MODULE",
  "IMPORT_RESOLVES_TO_MODULE",
  "IMPORT_RESOLVES_TO_SYMBOL",
  "MODULE_EXPORTS_SYMBOL",
  "ROUTE_DECLARED_IN_FILE",
  "ROUTE_HANDLED_BY_SYMBOL",
  "ROUTE_HAS_ENDPOINT",
  "MODULE_REEXPORTS_MODULE",
  "REEXPORT_RESOLVES_TO_SYMBOL",
  "CALLSITE_REFERENCES_SYMBOL",
  "DATA_OPERATION_READS_DATA_STORE",
  "DATA_OPERATION_WRITES_DATA_STORE",
  "DATA_OPERATION_DELETES_DATA_STORE",
  "DATA_OPERATION_TOUCHES_DATA_STORE",
  "FINDING_HAS_EVIDENCE",
] as const;

export const GraphEdgeKindSchema = z.enum(GRAPH_EDGE_KINDS);

export type GraphEdgeKind = (typeof GRAPH_EDGE_KINDS)[number];

/**
 * Roles a file can be detected as. Crosses the boundary inside `file_role_detected` facts, `file_role` graph nodes, convention matchers (`applies_to_file_roles`) and the MCP get_repo_map filter.
 */
export const FILE_ROLES = [
  "api_route",
  "server_module",
  "service_module",
  "data_access_module",
  "component",
  "ui_component",
  "hook_module",
  "schema_module",
  "test",
  "config",
  "cli_command_module",
  "core_module",
  "query_module",
  "factgraph_module",
  "adapter_module",
  "storage_module",
  "engine_bridge_module",
  "mcp_module",
  "docs",
  "package_manifest",
  "custom",
] as const;

export const FileRoleSchema = z.enum(FILE_ROLES);

export type FileRole = (typeof FILE_ROLES)[number];

/**
 * CV-2: what kind of caller a route serves. Conditions convention scope (`applies_to_route_flavors`) and carried across the boundary in `route_flavor_detected` facts.
 */
export const ROUTE_FLAVORS = [
  "api_route",
  "cron_job",
  "webhook_handler",
] as const;

export const RouteFlavorSchema = z.enum(ROUTE_FLAVORS);

export type RouteFlavor = (typeof ROUTE_FLAVORS)[number];

/**
 * Why a region of the repo could not be understood. Derived CLI-side from engine diagnostic codes, and referenced by the semantic capability contracts, whose parser_gap_kinds must be members of this list.
 */
export const PARSER_GAP_KINDS = [
  "unresolved_import",
  "unresolved_symbol",
  "unknown_file_role",
  "mixed_file_role",
  "unsupported_framework_pattern",
  "parser_error",
  "partial_parse",
  "dynamic_import_unresolved",
  "reflection_or_magic_detected",
] as const;

export const ParserGapKindSchema = z.enum(PARSER_GAP_KINDS);

export type ParserGapKind = (typeof PARSER_GAP_KINDS)[number];

/**
 * D-P3a: every convention kind, and where each one dispatches.
 *
 * The 23 kinds were evaluated by three mechanisms - a literal-match chain in check_command.rs, the
 * is_phase6_security_convention predicate beside it, and a separate chain in the CLI's run-check.ts -
 * with three more accepted by the schema and implemented nowhere. No single place listed all of them,
 * so a 24th kind with no evaluator would have been caught by nothing: `check` returns a clean pass for
 * a contract that enforces nothing.
 *
 * `dispatch` is now that place. The generated Rust ConventionDispatch is matched exhaustively by the
 * engine, so a new kind that names no target does not compile.
 *
 * dispatch values:
 *   engine_direct - a dedicated arm in crates/drift-engine/src/check_command.rs
 *   engine_phase6 - the shared Phase 6 evaluator in the same file
 *   cli           - an arm in packages/cli/src/check/run-check.ts
 *   none          - accepted by the schema, implemented by neither (UNIMPLEMENTED_CONVENTION_KINDS)
 *
 * `proposable` marks the kinds candidate inference can propose. It is exactly the set the engine's
 * candidate payload used to declare in its own hand-written enum.
 *
 * `security_contract` marks the kinds that carry a security boundary proof. Three lists claimed
 * to be this set and two of them agreed: SecurityContractKindSchema (13) and
 * EngineSecurityContractKindSchema (13) against EXPERIMENTAL_SECURITY_CONVENTION_KINDS (12),
 * which omitted api_route_forbids_secret_exposure - the flag that keeps every security kind
 * behind --experimental-security, missing the one kind whose whole subject is secrets.
 *
 * `requires_engine_source` marks the kinds whose engine evaluator re-reads the route file from
 * disk instead of working from the facts on the wire. All twelve security kinds do. Without
 * `repo_root` - which the wire protocol declares Option<String> - every one of them silently
 * produced nothing, and `check` reported a clean pass. See D-F1 in check_command.rs.
 */
export const CONVENTION_KINDS = [
  "api_route_no_direct_data_access",
  "api_route_requires_service_delegation",
  "api_route_requires_auth_helper",
  "middleware_must_cover_routes",
  "api_route_requires_request_validation",
  "api_route_forbids_untrusted_ssrf",
  "api_route_forbids_raw_sql_without_params",
  "api_route_cors_must_match_policy",
  "api_route_requires_csrf_for_mutation",
  "api_route_requires_rate_limit",
  "api_route_forbids_sensitive_response_fields",
  "api_route_forbids_secret_exposure",
  "session_object_must_come_from_trusted_helper",
  "api_route_requires_authorization",
  "api_route_requires_tenant_scope",
  "test_expected_for_changed_module",
  "custom_briefing",
  "file_role",
  "module_placement",
  "import_boundary",
  "entrypoint_flow",
  "canonical_helper_reuse",
  "required_change_checks",
] as const;

export const ConventionKindSchema = z.enum(CONVENTION_KINDS);

export type ConventionKind = (typeof CONVENTION_KINDS)[number];

/**
 * Where each convention kind is evaluated. The only list of all of them (D-P3a).
 */
export const CONVENTION_DISPATCH: Readonly<Record<ConventionKind, ConventionDispatch>> = {
  api_route_no_direct_data_access: "engine_direct",
  api_route_requires_service_delegation: "none",
  api_route_requires_auth_helper: "engine_direct",
  middleware_must_cover_routes: "none",
  api_route_requires_request_validation: "engine_direct",
  api_route_forbids_untrusted_ssrf: "engine_phase6",
  api_route_forbids_raw_sql_without_params: "engine_phase6",
  api_route_cors_must_match_policy: "engine_phase6",
  api_route_requires_csrf_for_mutation: "engine_phase6",
  api_route_requires_rate_limit: "engine_phase6",
  api_route_forbids_sensitive_response_fields: "engine_direct",
  api_route_forbids_secret_exposure: "engine_direct",
  session_object_must_come_from_trusted_helper: "engine_direct",
  api_route_requires_authorization: "engine_direct",
  api_route_requires_tenant_scope: "engine_direct",
  test_expected_for_changed_module: "none",
  custom_briefing: "none",
  file_role: "cli",
  module_placement: "cli",
  import_boundary: "cli",
  entrypoint_flow: "cli",
  canonical_helper_reuse: "cli",
  required_change_checks: "cli",
};

export const CONVENTION_DISPATCH_TARGETS = ["engine_direct","none","engine_phase6","cli"] as const;

export type ConventionDispatch = (typeof CONVENTION_DISPATCH_TARGETS)[number];

/** The kinds candidate inference may propose. */
export const CANDIDATE_CONVENTION_KINDS = [
  "api_route_no_direct_data_access",
  "api_route_requires_service_delegation",
  "api_route_requires_auth_helper",
  "middleware_must_cover_routes",
  "api_route_requires_request_validation",
  "api_route_forbids_untrusted_ssrf",
  "api_route_forbids_raw_sql_without_params",
  "api_route_cors_must_match_policy",
  "api_route_requires_csrf_for_mutation",
  "api_route_requires_rate_limit",
  "api_route_forbids_sensitive_response_fields",
  "api_route_forbids_secret_exposure",
  "session_object_must_come_from_trusted_helper",
  "api_route_requires_authorization",
  "api_route_requires_tenant_scope",
  "test_expected_for_changed_module",
  "custom_briefing",
] as const;

export const CandidateConventionKindSchema = z.enum(CANDIDATE_CONVENTION_KINDS);

/** Kinds that carry a security boundary proof, and are gated behind --experimental-security. */
export const SECURITY_CONTRACT_CONVENTION_KINDS = [
  "api_route_requires_auth_helper",
  "middleware_must_cover_routes",
  "api_route_requires_request_validation",
  "api_route_forbids_untrusted_ssrf",
  "api_route_forbids_raw_sql_without_params",
  "api_route_cors_must_match_policy",
  "api_route_requires_csrf_for_mutation",
  "api_route_requires_rate_limit",
  "api_route_forbids_sensitive_response_fields",
  "api_route_forbids_secret_exposure",
  "session_object_must_come_from_trusted_helper",
  "api_route_requires_authorization",
  "api_route_requires_tenant_scope",
] as const;

export const SecurityContractKindSchema = z.enum(SECURITY_CONTRACT_CONVENTION_KINDS);

/** Kinds whose engine evaluator re-reads the route file from disk (D-F1). */
export const SOURCE_READING_CONVENTION_KINDS = [
  "api_route_requires_auth_helper",
  "api_route_requires_request_validation",
  "api_route_forbids_untrusted_ssrf",
  "api_route_forbids_raw_sql_without_params",
  "api_route_cors_must_match_policy",
  "api_route_requires_csrf_for_mutation",
  "api_route_requires_rate_limit",
  "api_route_forbids_sensitive_response_fields",
  "api_route_forbids_secret_exposure",
  "session_object_must_come_from_trusted_helper",
  "api_route_requires_authorization",
  "api_route_requires_tenant_scope",
] as const;

/** The kinds the CLI evaluates rather than the engine - historically the agent contracts. */
export const CLI_EVALUATED_CONVENTION_KINDS = [
  "file_role",
  "module_placement",
  "import_boundary",
  "entrypoint_flow",
  "canonical_helper_reuse",
  "required_change_checks",
] as const;

export const CliEvaluatedConventionKindSchema = z.enum(CLI_EVALUATED_CONVENTION_KINDS);

/** The kinds no evaluator implements - accepting one would enforce nothing, silently. */
export const UNEVALUATED_CONVENTION_KINDS = [
  "api_route_requires_service_delegation",
  "middleware_must_cover_routes",
  "test_expected_for_changed_module",
  "custom_briefing",
] as const;

/**
 * D-S1: the one capability namespace.
 *
 * These ids are what may appear in EngineCapabilityStats (certified/required/missing),
 * EngineCompleteness.{required,missing}_capabilities, and therefore in ScanCapabilityReport and the
 * semantic coverage contract built from it.
 *
 * There used to be two namespaces with zero string overlap BY CONSTRUCTION: the engine emitted bare
 * names (`graph_stream`, `route_detection`) and BUILTIN_SEMANTIC_CAPABILITIES declared eight ids of
 * the form `ts.<name>.v1`. A hand-written translation table in packages/query/src/semantic-coverage.ts
 * was supposed to bridge them and named four capabilities the engine has never emitted
 * (`data_operations`, `data_operation_facts`, `fact_graph`, `route_flow`).
 *
 * The bare namespace won because it is the one on the wire: nine of the eleven sites that PRODUCE a
 * capability id already emitted bare names (both Rust capability_stats call sites, repo_completeness,
 * check_command's fourteen security labels, candidate_command, run-check.ts, convention-candidates.ts,
 * factgraph's two completeness entries, the TypeScript fallback's degraded list). The `ts.*.v1`
 * namespace appeared in exactly three places - the contract list itself and the two
 * DEFAULT_PREFLIGHT_CAPABILITIES references - none of which produced wire data.
 *
 * `engine_certified` marks the members crates/drift-engine/src/protocol.rs::certified_capabilities()
 * reports. `security` marks the members security_capabilities() reports (D-P3b).
 */
export const SCAN_CAPABILITIES = [
  "file_discovery",
  "syntax_facts",
  "static_imports",
  "import_resolution",
  "symbol_linking",
  "graph_stream",
  "route_detection",
  "route_flow",
  "data_operation_detection",
  "direct_data_access_check",
  "candidate_inference",
  "security_facts",
  "auth_boundary_facts",
  "control_flow_guard_dominance",
  "middleware_coverage",
  "request_validation_facts",
  "outbound_request_facts",
  "raw_sql_facts",
  "cors_policy_facts",
  "csrf_facts",
  "rate_limit_facts",
  "response_shape_facts",
  "secret_exposure",
  "session_trust",
  "authorization",
  "tenant_scope",
  "data_access_inference",
  "dynamic_imports",
  "computed_calls",
  "graph",
  "graph_evidence",
  "deterministic_enforcement",
] as const;

export const ScanCapabilitySchema = z.enum(SCAN_CAPABILITIES);

export type ScanCapability = (typeof SCAN_CAPABILITIES)[number];

/** The capabilities the Rust engine reports as certified. */
export const ENGINE_CERTIFIED_SCAN_CAPABILITIES = [
  "file_discovery",
  "syntax_facts",
  "static_imports",
  "import_resolution",
  "symbol_linking",
  "graph_stream",
  "route_detection",
  "route_flow",
  "data_operation_detection",
  "direct_data_access_check",
  "candidate_inference",
  "security_facts",
  "auth_boundary_facts",
  "control_flow_guard_dominance",
] as const;

/** The capabilities the security layer reports on (D-P3b). */
export const SECURITY_SCAN_CAPABILITIES = [
  "security_facts",
  "auth_boundary_facts",
  "control_flow_guard_dominance",
  "middleware_coverage",
  "request_validation_facts",
  "outbound_request_facts",
  "raw_sql_facts",
  "cors_policy_facts",
  "csrf_facts",
  "rate_limit_facts",
  "response_shape_facts",
  "secret_exposure",
  "session_trust",
  "authorization",
  "tenant_scope",
] as const;

export const SecurityCapabilityNameSchema = z.enum(SECURITY_SCAN_CAPABILITIES);

export type SecurityCapabilityName = (typeof SECURITY_SCAN_CAPABILITIES)[number];

/**
 * Why a session object could not be proven trusted. PROOF-LEVEL vocabulary: it says why the proof failed. The FINDING-level code a user sees (SecurityMissingProofCodeSchema) is separate and is derived from this by the phase4 finding-reason mapping in check_command.rs. The two are deliberately different vocabularies; mapping between them must be total.
 */
export const SESSION_TRUST_REASONS = [
  "derived_from_request",
  "unknown_helper",
  "missing_auth_guard",
  "parser_gap",
] as const;

export const SessionTrustReasonSchema = z.enum(SESSION_TRUST_REASONS);

export type SessionTrustReason = (typeof SESSION_TRUST_REASONS)[number];

/**
 * Why an authorization proof could not be completed. PROOF-LEVEL vocabulary, on `authorization.missing[].reason`. The list carries two spellings of the same three concepts - an older `no_authorization_guard`/`guard_not_dominating_sink` pair and the newer `authorization_guard_missing`/`authorization_guard_not_dominating_sink` - because the enum was WIDENED rather than migrated when the engine's wording changed. Only the newer spelling has a producer today; the older one is reserved, because the schema is applied on read and stored rows may still hold it.
 */
export const AUTHORIZATION_MISSING_REASONS = [
  "no_authorization_guard",
  "guard_not_dominating_sink",
  "unknown_policy_helper",
  "session_not_trusted",
  "authorization_guard_missing",
  "authorization_guard_not_dominating_sink",
] as const;

export const AuthorizationMissingReasonSchema = z.enum(AUTHORIZATION_MISSING_REASONS);

export type AuthorizationMissingReason = (typeof AUTHORIZATION_MISSING_REASONS)[number];

/**
 * Why a tenant-scope proof could not be completed. PROOF-LEVEL vocabulary, on `tenant.missing[].reason`. Widened the same way authorization_missing_reason was: the first three members are the spelling the original design named, the last three are the spelling the engine emits, and `parser_gap` is a fourth concept with no producer at all. Only the newer three are constructed; the rest are reserved rather than deleted, because the schema is applied on read.
 */
export const TENANT_MISSING_REASONS = [
  "no_tenant_predicate",
  "untrusted_tenant_source",
  "predicate_not_bound_to_query",
  "parser_gap",
  "tenant_predicate_missing",
  "tenant_source_untrusted",
  "tenant_predicate_not_bound_to_query",
] as const;

export const TenantMissingReasonSchema = z.enum(TENANT_MISSING_REASONS);

export type TenantMissingReason = (typeof TENANT_MISSING_REASONS)[number];
