-- Wrap current_setting()/auth.* calls in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row.
-- Predicate-equivalent (row visibility unchanged). Generated by 'pgrls fix --rule
-- PERF001' and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'api_keys_isolation' on public.api_keys so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY api_keys_isolation ON public.api_keys
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_agent_registry_isolation' on public.cloud_agent_registry so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_agent_registry_isolation ON public.cloud_agent_registry
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_agent_trust_isolation' on public.cloud_agent_trust so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_agent_trust_isolation ON public.cloud_agent_trust
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'audit_tenant_isolation' on public.cloud_audit_log so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY audit_tenant_isolation ON public.cloud_audit_log
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_audit_snapshots_isolation' on public.cloud_audit_snapshots so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_audit_snapshots_isolation ON public.cloud_audit_snapshots
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_boundaries_isolation' on public.cloud_boundaries so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_boundaries_isolation ON public.cloud_boundaries
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_bridge_events_isolation' on public.cloud_bridge_events so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_bridge_events_isolation ON public.cloud_bridge_events
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_bridge_memories_isolation' on public.cloud_bridge_memories so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_bridge_memories_isolation ON public.cloud_bridge_memories
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_bridge_metrics_isolation' on public.cloud_bridge_metrics so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_bridge_metrics_isolation ON public.cloud_bridge_metrics
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_call_edges_isolation' on public.cloud_call_edges so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_call_edges_isolation ON public.cloud_call_edges
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_causal_edges_isolation' on public.cloud_causal_edges so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_causal_edges_isolation ON public.cloud_causal_edges
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_causal_evidence_isolation' on public.cloud_causal_evidence so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_causal_evidence_isolation ON public.cloud_causal_evidence
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_consolidation_metrics_isolation' on public.cloud_consolidation_metrics so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_consolidation_metrics_isolation ON public.cloud_consolidation_metrics
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_constants_isolation' on public.cloud_constants so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_constants_isolation ON public.cloud_constants
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_constraint_results_isolation' on public.cloud_constraint_results so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_constraint_results_isolation ON public.cloud_constraint_results
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_constraints_isolation' on public.cloud_constraints so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_constraints_isolation ON public.cloud_constraints
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_contract_mismatches_isolation' on public.cloud_contract_mismatches so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_contract_mismatches_isolation ON public.cloud_contract_mismatches
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_contracts_isolation' on public.cloud_contracts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_contracts_isolation ON public.cloud_contracts
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_conventions_isolation' on public.cloud_conventions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_conventions_isolation ON public.cloud_conventions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_cortex_degradation_log_isolation' on public.cloud_cortex_degradation_log so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_cortex_degradation_log_isolation ON public.cloud_cortex_degradation_log
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_coupling_cycles_isolation' on public.cloud_coupling_cycles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_coupling_cycles_isolation ON public.cloud_coupling_cycles
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_coupling_metrics_isolation' on public.cloud_coupling_metrics so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_coupling_metrics_isolation ON public.cloud_coupling_metrics
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_crypto_findings_isolation' on public.cloud_crypto_findings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_crypto_findings_isolation ON public.cloud_crypto_findings
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_data_access_isolation' on public.cloud_data_access so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_data_access_isolation ON public.cloud_data_access
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_decisions_isolation' on public.cloud_decisions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_decisions_isolation ON public.cloud_decisions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_decomposition_decisions_isolation' on public.cloud_decomposition_decisions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_decomposition_decisions_isolation ON public.cloud_decomposition_decisions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_degradation_alerts_isolation' on public.cloud_degradation_alerts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_degradation_alerts_isolation ON public.cloud_degradation_alerts
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_detections_isolation' on public.cloud_detections so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_detections_isolation ON public.cloud_detections
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_dna_genes_isolation' on public.cloud_dna_genes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_dna_genes_isolation ON public.cloud_dna_genes
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_dna_mutations_isolation' on public.cloud_dna_mutations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_dna_mutations_isolation ON public.cloud_dna_mutations
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_drift_snapshots_isolation' on public.cloud_drift_snapshots so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_drift_snapshots_isolation ON public.cloud_drift_snapshots
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_embedding_models_isolation' on public.cloud_embedding_models so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_embedding_models_isolation ON public.cloud_embedding_models
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_env_variables_isolation' on public.cloud_env_variables so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_env_variables_isolation ON public.cloud_env_variables
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_error_gaps_isolation' on public.cloud_error_gaps so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_error_gaps_isolation ON public.cloud_error_gaps
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_feedback_isolation' on public.cloud_feedback so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_feedback_isolation ON public.cloud_feedback
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_file_stats_isolation' on public.cloud_file_stats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_file_stats_isolation ON public.cloud_file_stats
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_functions_isolation' on public.cloud_functions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_functions_isolation ON public.cloud_functions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_gate_results_isolation' on public.cloud_gate_results so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_gate_results_isolation ON public.cloud_gate_results
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_grounding_results_isolation' on public.cloud_grounding_results so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_grounding_results_isolation ON public.cloud_grounding_results
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_grounding_snapshots_isolation' on public.cloud_grounding_snapshots so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_grounding_snapshots_isolation ON public.cloud_grounding_snapshots
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_health_trends_isolation' on public.cloud_health_trends so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_health_trends_isolation ON public.cloud_health_trends
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_impact_scores_isolation' on public.cloud_impact_scores so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_impact_scores_isolation ON public.cloud_impact_scores
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memories_isolation' on public.cloud_memories so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memories_isolation ON public.cloud_memories
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_audit_log_isolation' on public.cloud_memory_audit_log so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_audit_log_isolation ON public.cloud_memory_audit_log
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_constraints_isolation' on public.cloud_memory_constraints so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_constraints_isolation ON public.cloud_memory_constraints
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_contradictions_isolation' on public.cloud_memory_contradictions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_contradictions_isolation ON public.cloud_memory_contradictions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_events_isolation' on public.cloud_memory_events so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_events_isolation ON public.cloud_memory_events
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_files_isolation' on public.cloud_memory_files so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_files_isolation ON public.cloud_memory_files
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_functions_isolation' on public.cloud_memory_functions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_functions_isolation ON public.cloud_memory_functions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_namespaces_isolation' on public.cloud_memory_namespaces so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_namespaces_isolation ON public.cloud_memory_namespaces
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_patterns_isolation' on public.cloud_memory_patterns so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_patterns_isolation ON public.cloud_memory_patterns
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_projections_isolation' on public.cloud_memory_projections so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_projections_isolation ON public.cloud_memory_projections
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_relationships_isolation' on public.cloud_memory_relationships so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_relationships_isolation ON public.cloud_memory_relationships
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_snapshots_isolation' on public.cloud_memory_snapshots so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_snapshots_isolation ON public.cloud_memory_snapshots
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_validation_isolation' on public.cloud_memory_validation so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_validation_isolation ON public.cloud_memory_validation
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_memory_versions_isolation' on public.cloud_memory_versions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_memory_versions_isolation ON public.cloud_memory_versions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_migration_corrections_isolation' on public.cloud_migration_corrections so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_migration_corrections_isolation ON public.cloud_migration_corrections
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_migration_modules_isolation' on public.cloud_migration_modules so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_migration_modules_isolation ON public.cloud_migration_modules
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_migration_projects_isolation' on public.cloud_migration_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_migration_projects_isolation ON public.cloud_migration_projects
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_namespace_permissions_isolation' on public.cloud_namespace_permissions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_namespace_permissions_isolation ON public.cloud_namespace_permissions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_outliers_isolation' on public.cloud_outliers so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_outliers_isolation ON public.cloud_outliers
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_owasp_findings_isolation' on public.cloud_owasp_findings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_owasp_findings_isolation ON public.cloud_owasp_findings
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_pattern_confidence_isolation' on public.cloud_pattern_confidence so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_pattern_confidence_isolation ON public.cloud_pattern_confidence
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_policy_results_isolation' on public.cloud_policy_results so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_policy_results_isolation ON public.cloud_policy_results
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_provenance_log_isolation' on public.cloud_provenance_log so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_provenance_log_isolation ON public.cloud_provenance_log
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_reclassification_history_isolation' on public.cloud_reclassification_history so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_reclassification_history_isolation ON public.cloud_reclassification_history
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_reclassification_signals_isolation' on public.cloud_reclassification_signals so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_reclassification_signals_isolation ON public.cloud_reclassification_signals
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_scan_history_isolation' on public.cloud_scan_history so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_scan_history_isolation ON public.cloud_scan_history
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_secrets_isolation' on public.cloud_secrets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_secrets_isolation ON public.cloud_secrets
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_simulations_isolation' on public.cloud_simulations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_simulations_isolation ON public.cloud_simulations
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_taint_flows_isolation' on public.cloud_taint_flows so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_taint_flows_isolation ON public.cloud_taint_flows
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_test_coverage_isolation' on public.cloud_test_coverage so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_test_coverage_isolation ON public.cloud_test_coverage
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_test_quality_isolation' on public.cloud_test_quality so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_test_quality_isolation ON public.cloud_test_quality
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_violations_isolation' on public.cloud_violations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_violations_isolation ON public.cloud_violations
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_wrappers_isolation' on public.cloud_wrappers so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY cloud_wrappers_isolation ON public.cloud_wrappers
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'invitations_tenant_isolation' on public.invitations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY invitations_tenant_isolation ON public.invitations
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'ip_allowlist_tenant_isolation' on public.ip_allowlist so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY ip_allowlist_tenant_isolation ON public.ip_allowlist
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'projects_isolation' on public.projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY projects_isolation ON public.projects
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'scim_group_mappings_tenant_isolation' on public.scim_group_mappings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY scim_group_mappings_tenant_isolation ON public.scim_group_mappings
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'scim_tokens_tenant_isolation' on public.scim_tokens so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY scim_tokens_tenant_isolation ON public.scim_tokens
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'subscriptions_isolation' on public.subscriptions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY subscriptions_isolation ON public.subscriptions
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'teams_isolation' on public.teams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY teams_isolation ON public.teams
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'tenants_isolation' on public.tenants so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY tenants_isolation ON public.tenants
    USING (id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'utm_isolation' on public.user_tenant_mappings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY utm_isolation ON public.user_tenant_mappings
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'webhook_deliveries_tenant_isolation' on public.webhook_deliveries so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY webhook_deliveries_tenant_isolation ON public.webhook_deliveries
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'webhook_endpoints_tenant_isolation' on public.webhook_endpoints so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY webhook_endpoints_tenant_isolation ON public.webhook_endpoints
    USING (tenant_id = CAST((SELECT current_setting(CAST('app.tenant_id' AS text), TRUE)) AS uuid));
