#!/usr/bin/env bash
# Reclaim disk space during a long unattended run.
#
# Every tier removes only regenerable artifacts, in increasing order of what it costs to rebuild.
# Nothing here touches the evaluation repos (pinned SHAs - re-cloning would change what the suite
# measures), the git working tree, or anything outside Drift's own caches.
#
#   ./scripts/reclaim-disk.sh            # run tiers until above the target
#   ./scripts/reclaim-disk.sh 8          # target 8 GB free
#
# Exits 0 if the target is met, 1 if every tier ran and it still is not.

set -uo pipefail

TARGET_GB="${1:-6}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

free_gb() {
  df -k "$HOME" | tail -1 | awk '{printf "%.1f", $4/1024/1024}'
}

report() { echo "  free: $(free_gb) GB  (target ${TARGET_GB})"; }

met() {
  awk -v a="$(free_gb)" -v b="$TARGET_GB" 'BEGIN { exit !(a >= b) }'
}

echo "reclaim-disk: starting at $(free_gb) GB free, target ${TARGET_GB} GB"

# Tier 1 - Drift state and scratch dirs. Free, instantly regenerated by the next scan.
# The eval harness uses its own temp HOME per repo, so ~/.drift only holds manual-run state.
if ! met; then
  echo "tier 1: drift state and scratch directories"
  rm -rf "$HOME/.drift" 2>/dev/null
  rm -rf /tmp/drift-* /tmp/t[0-9]* /tmp/f4* /tmp/a[0-9]* /tmp/eprepro /tmp/tyrepro /tmp/fx_* 2>/dev/null
  # Harness temp homes, which live under the platform temp dir rather than /tmp on macOS.
  find /var/folders -maxdepth 4 -type d -name "drift-eval-*" -exec rm -rf {} + 2>/dev/null
  find /var/folders -maxdepth 4 -type d -name "drift-cli-*" -exec rm -rf {} + 2>/dev/null
  find /var/folders -maxdepth 4 -type d -name "drift-*-home-*" -exec rm -rf {} + 2>/dev/null
  report
fi

# Tier 2 - debug build artifacts. Rebuilt automatically by `cargo test`, ~1-2 minutes.
# Release is deliberately left alone: the CLI and harness invoke it, and a missing release
# binary turns every subsequent verification into a false failure.
if ! met; then
  echo "tier 2: cargo debug artifacts (release kept - the harness needs it)"
  rm -rf "$REPO_ROOT/target/debug" 2>/dev/null
  report
fi

# Tier 3 - package caches. This tier IS a correctness risk, despite what it used to claim here.
#
# `pnpm store prune` is not a cache eviction: pnpm's node_modules are links into the global store, so
# pruning it leaves every workspace package unresolvable. Recovery needs network, which is why this
# tier used to be described as costing "network, not correctness" - but the tree is broken from the
# prune until that reinstall happens, and the breakage does not look like a broken tree. `drift
# --version` still answers, because it imports neither @drift/storage nor better-sqlite3, so the first
# symptom is an eval run failing as though the engine were at fault. That cost a full run to
# misdiagnose.
#
# Left in, because at this tier the alternative is failing to reclaim at all - but it announces the
# reinstall it just made necessary rather than reporting a silent success.
if ! met; then
  echo "tier 3: package caches"
  rm -rf "$HOME/.cargo/registry/cache" 2>/dev/null
  if command -v pnpm >/dev/null; then
    pnpm store prune >/dev/null 2>&1
    echo "  NOTE: pruned the pnpm store, which unlinks workspace packages."
    echo "        Run 'pnpm install --recursive && pnpm build' before any CLI, test or eval run."
  fi
  report
fi

# Tier 4 - incremental compilation state. Slower rebuilds, nothing else.
if ! met; then
  echo "tier 4: cargo incremental state"
  rm -rf "$REPO_ROOT/target/release/incremental" 2>/dev/null
  find "$REPO_ROOT/target" -maxdepth 2 -name ".fingerprint" -exec rm -rf {} + 2>/dev/null
  report
fi

if met; then
  echo "reclaim-disk: ok, $(free_gb) GB free"
  exit 0
fi

# Deliberately not reclaimed: the seven evaluation repos. They are pinned to specific SHAs and
# re-cloning would silently change what the suite measures, which is worse than being short on
# space. Surface it instead of guessing.
echo "reclaim-disk: still only $(free_gb) GB free after every tier."
echo "Remaining large, deliberately untouched:"
du -sh "$HOME/drift-falsification/repos"/* 2>/dev/null | sort -rh | head -5
echo "Evaluation repos are pinned to SHAs; removing them changes what the suite measures."
exit 1
