#!/usr/bin/env node
/**
 * Emit the cross-boundary vocabularies into Rust and TypeScript from vocabulary/vocabulary.json.
 *
 *   node vocabulary/generate.mjs           write the generated files
 *   node vocabulary/generate.mjs --check   exit 1 if the committed files are stale
 *
 * The outputs are committed rather than produced by a build script, for two reasons. `cargo build`
 * and `tsc` must work in a fresh checkout without a Node step in front of them, and a generated file
 * that nobody can read is a worse source of truth than a hand-written one - the point of this change
 * is that the two sides can be DIFFED, not that they are hidden.
 *
 * Staleness is caught by scripts/vocabulary-parity.mjs, which runs this in --check mode, so an edit
 * to the manifest without a regenerate fails CI rather than shipping a third copy of the vocabulary.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
export const MANIFEST_PATH = join(repoRoot, "vocabulary/vocabulary.json");
export const RUST_OUTPUT_PATH = join(repoRoot, "crates/drift-engine/src/vocabulary.rs");
export const TS_OUTPUT_PATH = join(repoRoot, "packages/vocabulary/src/index.ts");

const BANNER_LINES = [
  "@generated by vocabulary/generate.mjs from vocabulary/vocabulary.json. DO NOT EDIT.",
  "",
  "Run `node vocabulary/generate.mjs` after changing the manifest.",
  "scripts/vocabulary-parity.mjs fails when this file and the manifest disagree."
];

export function readManifest() {
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}

/** Wire string -> Rust variant. Derived rather than declared so the two cannot be edited apart. */
export function rustVariant(wire) {
  return wire
    .toLowerCase()
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Wire string -> SCREAMING_SNAKE, for TypeScript const names derived from a member. */
function screaming(wire) {
  return wire.toUpperCase();
}

export function normalizedMembers(vocabulary) {
  return vocabulary.members.map((member) =>
    typeof member === "string" ? { wire: member } : member
  );
}

function docLines(doc) {
  return Array.isArray(doc) ? doc : [doc];
}

/**
 * Every member must yield a distinct Rust variant. Two members that PascalCase to the same name
 * would produce a Rust file that does not compile, which is a loud failure - but the message would
 * point at generated code rather than at the manifest line that caused it.
 */
function assertDistinctVariants(name, members) {
  const seen = new Map();
  for (const member of members) {
    const variant = rustVariant(member.wire);
    if (seen.has(variant)) {
      throw new Error(
        `vocabulary "${name}": "${member.wire}" and "${seen.get(variant)}" both PascalCase to ` +
          `${variant}. Rename one, or the generated Rust enum has two variants with one name.`
      );
    }
    seen.set(variant, member.wire);
  }
}

function rustEnum(name, vocabulary) {
  const members = normalizedMembers(vocabulary);
  assertDistinctVariants(name, members);
  const enumName = vocabulary.rust_enum;
  const lines = [];

  for (const line of docLines(vocabulary.doc)) {
    lines.push(line ? `/// ${line}` : "///");
  }
  lines.push("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]");
  lines.push(`pub enum ${enumName} {`);
  for (const member of members) {
    lines.push(`    ${rustVariant(member.wire)},`);
  }
  lines.push("}");
  lines.push("");
  lines.push(`impl ${enumName} {`);
  lines.push("    /// Every member, in manifest order.");
  lines.push(`    pub const ALL: &'static [${enumName}] = &[`);
  for (const member of members) {
    lines.push(`        ${enumName}::${rustVariant(member.wire)},`);
  }
  lines.push("    ];");
  lines.push("");
  lines.push("    /// The string this member takes on the wire.");
  lines.push("    pub fn as_wire(self) -> &'static str {");
  lines.push("        match self {");
  for (const member of members) {
    lines.push(`            ${enumName}::${rustVariant(member.wire)} => "${member.wire}",`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// Parse a wire string. `None` is an unknown member, never a silently dropped one.");
  lines.push("    pub fn from_wire(value: &str) -> Option<Self> {");
  lines.push("        match value {");
  for (const member of members) {
    lines.push(`            "${member.wire}" => Some(${enumName}::${rustVariant(member.wire)}),`);
  }
  lines.push("            _ => None,");
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// Every member's wire string, sorted, for the engine/CLI vocabulary handshake.");
  lines.push("    pub fn all_wire_names() -> Vec<String> {");
  lines.push("        let mut names: Vec<String> = Self::ALL");
  lines.push("            .iter()");
  lines.push("            .map(|member| member.as_wire().to_string())");
  lines.push("            .collect();");
  lines.push("        names.sort();");
  lines.push("        names");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push(`impl std::fmt::Display for ${enumName} {`);
  lines.push("    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
  lines.push("        formatter.write_str(self.as_wire())");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push(`impl serde::Serialize for ${enumName} {`);
  lines.push("    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {");
  lines.push("        serializer.serialize_str(self.as_wire())");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push(`impl<'de> serde::Deserialize<'de> for ${enumName} {`);
  lines.push("    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {");
  lines.push("        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;");
  lines.push(`        ${enumName}::from_wire(&raw).ok_or_else(|| {`);
  lines.push("            serde::de::Error::custom(format!(");
  lines.push(`                "unknown ${name} \\"{raw}\\": this engine and its caller disagree about the ${name} vocabulary"`);
  lines.push("            ))");
  lines.push("        })");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

/**
 * Extra Rust emitted for a vocabulary that carries member fields.
 *
 * `convention_kind.dispatch` becomes its own enum plus an exhaustive accessor: that is the whole
 * point of D-P3a, because the engine then matches on ConventionDispatch and a kind with no target
 * fails to compile rather than falling out of a chain of `else if`s into `continue`.
 */
function rustMemberFieldExtras(name, vocabulary) {
  const members = normalizedMembers(vocabulary);
  const enumName = vocabulary.rust_enum;
  const lines = [];

  if (name === "convention_kind") {
    const dispatches = [...new Set(members.map((member) => member.dispatch))];
    lines.push("/// Where a convention kind is evaluated. Exhaustively matched by the engine.");
    lines.push("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]");
    lines.push("pub enum ConventionDispatch {");
    for (const dispatch of dispatches) {
      lines.push(`    ${rustVariant(dispatch)},`);
    }
    lines.push("}");
    lines.push("");
    lines.push(`impl ${enumName} {`);
    lines.push("    /// The evaluator that owns this kind.");
    lines.push("    pub fn dispatch(self) -> ConventionDispatch {");
    lines.push("        match self {");
    for (const member of members) {
      lines.push(
        `            ${enumName}::${rustVariant(member.wire)} => ConventionDispatch::${rustVariant(member.dispatch)},`
      );
    }
    lines.push("        }");
    lines.push("    }");
    lines.push("");
    lines.push("    /// Whether candidate inference may propose this kind.");
    lines.push("    pub fn proposable(self) -> bool {");
    lines.push("        match self {");
    for (const member of members) {
      lines.push(`            ${enumName}::${rustVariant(member.wire)} => ${member.proposable},`);
    }
    lines.push("        }");
    lines.push("    }");
    lines.push("");
    lines.push("    /// Whether this kind's engine evaluator re-reads the route file from disk.");
    lines.push("    ///");
    lines.push("    /// True for every kind whose evaluator calls `read_repo_file`. Such a kind cannot be");
    lines.push("    /// evaluated at all without `repo_root`, and `repo_root` is optional on the wire.");
    lines.push("    pub fn requires_engine_source(self) -> bool {");
    lines.push("        match self {");
    for (const member of members) {
      lines.push(`            ${enumName}::${rustVariant(member.wire)} => ${member.requires_engine_source},`);
    }
    lines.push("        }");
    lines.push("    }");
    lines.push("}");
  }

  if (name === "scan_capability") {
    lines.push(`impl ${enumName} {`);
    lines.push("    /// The capabilities crates/drift-engine reports as certified.");
    lines.push(`    pub const ENGINE_CERTIFIED: &'static [${enumName}] = &[`);
    for (const member of members.filter((entry) => entry.engine_certified)) {
      lines.push(`        ${enumName}::${rustVariant(member.wire)},`);
    }
    lines.push("    ];");
    lines.push("");
    lines.push("    /// The capabilities the security layer reports on (D-P3b).");
    lines.push(`    pub const SECURITY: &'static [${enumName}] = &[`);
    for (const member of members.filter((entry) => entry.security)) {
      lines.push(`        ${enumName}::${rustVariant(member.wire)},`);
    }
    lines.push("    ];");
    lines.push("}");
  }

  return lines.length > 0 ? lines.join("\n") : null;
}

/**
 * Run the rendered Rust through rustfmt.
 *
 * `cargo fmt --all` formats this file like any other, so a generator that emits anything rustfmt
 * would rewrap makes the format check and the parity gate mutually unsatisfiable: regenerate and
 * `cargo fmt --check` fails, format and the parity gate fails. Formatting here means the committed
 * file is a fixed point of both.
 *
 * A missing or failing rustfmt is a hard error, not a fallback to unformatted output - the fallback
 * would produce exactly the oscillation this exists to prevent, and quietly.
 */
function rustfmt(source) {
  const result = spawnSync("rustfmt", ["--edition", "2024", "--emit", "stdout", "--quiet"], {
    input: source,
    encoding: "utf8"
  });
  if (result.error || result.status !== 0) {
    throw new Error(
      `rustfmt failed while formatting the generated vocabulary (${result.error?.message ?? result.stderr?.trim() ?? `exit ${result.status}`}). ` +
        "It is required: `cargo fmt --all` formats the generated file, so unformatted output would " +
        "make the format check and scripts/vocabulary-parity.mjs contradict each other."
    );
  }
  return result.stdout;
}

export function renderRust(manifest) {
  const chunks = [];
  chunks.push(BANNER_LINES.map((line) => (line ? `// ${line}` : "//")).join("\n"));

  for (const [name, vocabulary] of Object.entries(manifest.vocabularies)) {
    if (!vocabulary.rust_enum) {
      continue;
    }
    chunks.push(rustEnum(name, vocabulary));
    const extras = rustMemberFieldExtras(name, vocabulary);
    if (extras) {
      chunks.push(extras);
    }
  }

  return rustfmt(`${chunks.join("\n\n")}\n`);
}

function tsBlock(name, vocabulary) {
  const members = normalizedMembers(vocabulary);
  const lines = [];

  lines.push("/**");
  for (const line of docLines(vocabulary.doc)) {
    lines.push(line ? ` * ${line}` : " *");
  }
  lines.push(" */");
  lines.push(`export const ${vocabulary.ts_const} = [`);
  for (const member of members) {
    lines.push(`  "${member.wire}",`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(`export const ${vocabulary.ts_schema} = z.enum(${vocabulary.ts_const});`);
  lines.push("");
  const typeName = vocabulary.ts_schema.replace(/Schema$/, "");
  lines.push(`export type ${typeName} = (typeof ${vocabulary.ts_const})[number];`);

  if (name === "convention_kind") {
    lines.push("");
    lines.push("/**");
    lines.push(" * Where each convention kind is evaluated. The only list of all of them (D-P3a).");
    lines.push(" */");
    lines.push("export const CONVENTION_DISPATCH: Readonly<Record<ConventionKind, ConventionDispatch>> = {");
    for (const member of members) {
      lines.push(`  ${member.wire}: "${member.dispatch}",`);
    }
    lines.push("};");
    lines.push("");
    lines.push(`export const CONVENTION_DISPATCH_TARGETS = ${JSON.stringify([
      ...new Set(members.map((member) => member.dispatch))
    ])} as const;`);
    lines.push("");
    lines.push("export type ConventionDispatch = (typeof CONVENTION_DISPATCH_TARGETS)[number];");
    lines.push("");
    lines.push("/** The kinds candidate inference may propose. */");
    lines.push("export const CANDIDATE_CONVENTION_KINDS = [");
    for (const member of members.filter((entry) => entry.proposable)) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("export const CandidateConventionKindSchema = z.enum(CANDIDATE_CONVENTION_KINDS);");
    lines.push("");
    lines.push("/** Kinds that carry a security boundary proof, and are gated behind --experimental-security. */");
    lines.push("export const SECURITY_CONTRACT_CONVENTION_KINDS = [");
    for (const member of members.filter((entry) => entry.security_contract)) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("export const SecurityContractKindSchema = z.enum(SECURITY_CONTRACT_CONVENTION_KINDS);");
    lines.push("");
    lines.push("/** Kinds whose engine evaluator re-reads the route file from disk (D-F1). */");
    lines.push("export const SOURCE_READING_CONVENTION_KINDS = [");
    for (const member of members.filter((entry) => entry.requires_engine_source)) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("/** The kinds the CLI evaluates rather than the engine - historically the agent contracts. */");
    lines.push("export const CLI_EVALUATED_CONVENTION_KINDS = [");
    for (const member of members.filter((entry) => entry.dispatch === "cli")) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("export const CliEvaluatedConventionKindSchema = z.enum(CLI_EVALUATED_CONVENTION_KINDS);");
    lines.push("");
    lines.push("/** The kinds no evaluator implements - accepting one would enforce nothing, silently. */");
    lines.push("export const UNEVALUATED_CONVENTION_KINDS = [");
    for (const member of members.filter((entry) => entry.dispatch === "none")) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
  }

  if (name === "scan_capability") {
    lines.push("");
    lines.push("/** The capabilities the Rust engine reports as certified. */");
    lines.push("export const ENGINE_CERTIFIED_SCAN_CAPABILITIES = [");
    for (const member of members.filter((entry) => entry.engine_certified)) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("/** The capabilities the security layer reports on (D-P3b). */");
    lines.push("export const SECURITY_SCAN_CAPABILITIES = [");
    for (const member of members.filter((entry) => entry.security)) {
      lines.push(`  "${member.wire}",`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("export const SecurityCapabilityNameSchema = z.enum(SECURITY_SCAN_CAPABILITIES);");
    lines.push("");
    lines.push("export type SecurityCapabilityName = (typeof SECURITY_SCAN_CAPABILITIES)[number];");
  }

  return lines.join("\n");
}

export function renderTypeScript(manifest) {
  const chunks = [];
  chunks.push(BANNER_LINES.map((line) => (line ? `// ${line}` : "//")).join("\n"));
  chunks.push('import { z } from "zod";');

  for (const [name, vocabulary] of Object.entries(manifest.vocabularies)) {
    if (!vocabulary.ts_const) {
      continue;
    }
    chunks.push(tsBlock(name, vocabulary));
  }

  return `${chunks.join("\n\n")}\n`;
}

function main() {
  const manifest = readManifest();
  const outputs = [
    { path: RUST_OUTPUT_PATH, content: renderRust(manifest) },
    { path: TS_OUTPUT_PATH, content: renderTypeScript(manifest) }
  ];

  if (process.argv.includes("--check")) {
    const stale = outputs.filter((output) => {
      try {
        return readFileSync(output.path, "utf8") !== output.content;
      } catch {
        return true;
      }
    });
    if (stale.length > 0) {
      console.error(
        `vocabulary: ${stale.length} generated file(s) do not match vocabulary/vocabulary.json:\n` +
          stale.map((output) => `  ${output.path.replace(repoRoot, "")}`).join("\n") +
          "\nRun `node vocabulary/generate.mjs`."
      );
      process.exit(1);
    }
    console.log(`vocabulary: ${outputs.length} generated file(s) match the manifest.`);
    return;
  }

  for (const output of outputs) {
    writeFileSync(output.path, output.content);
    console.log(`wrote ${output.path.replace(repoRoot, "")}`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
